### ISSUE TITLE
IDE should display filename and line number when syntax error is detected

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#1]
currently it is only showing colum

**Comment by giuliomoro** [comment]
5d0269aad6243549038352d49488b54cc3f5e5e2 @LBDonovan  makes it show the line number.
It would be helpful to show the file name as well later on, if at all possible.

**Comment by LBDonovan** [comment]
Currently the error messages do show the file, but only if the error is in a different file to the one currently open. Would it be better to always show the file?

**Comment by giuliomoro** [comment]
Then I guess it is fine as it is.
