### ISSUE TITLE
Changes to .h files are not compiled unless render.cpp has been edited.

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#10]
This should be noted on the wiki.

Solution is to edit render.cpp or clean project before running.

**Comment by LBDonovan** [comment]
@giuliomoro I'm fairly sure this is a problem with the Makefile, probably something to do with how it reads the .d dependency files. This post details the issue:

http://stackoverflow.com/questions/297514/how-can-i-have-a-makefile-automatically-rebuild-source-files-that-include-a-modi

The .d file seems to be created correctly, but for whatever reason a recompile is not forced. I know this did not happen with the old IDE Makefile, but I'm afraid I don't know why...

**Comment by giuliomoro** [comment]
Sure it is a Makefile issue!
