### ISSUE TITLE
IDE scopeTriggerTask uses CPU when scope window is closed

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#108]
about 0.8% is constantly in use by scopeTriggerTask, even if the scope window is closed and/or the IDE is stopped.

**Comment by LBDonovan** [comment]
I can't reproduce this, when I close the scope window it goes down to 0. Are you sure you didn't have a scope tab open somewhere, maybe in a different browser or something? 

I'm pretty sure it should never get scheduled when the scope window is closed.

**Comment by giuliomoro** [comment]
It is confirmed in `dev`: if you start a program with a scope (e.g.: an empty or basic Pd patch, where nothing is sent to the scope, but the scope is created), but no scope window, that thread will use CPU. If you open and then close the scope window, it will stop using CPU. Sounds like an initialization issue.

Yet, in the `scope-dev` branch it seems to be fixed.

Feel free to mark issue as "resolved" if it is resolved
