### ISSUE TITLE
IDE scope CPU usage

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#115]
re: CPU usage of doFFT() :

```
        // prepare the FFT input & do windowing
        for (int i=0; i<FFTLength; i++){
            inFFT[i].r = (ne10_float32_t)(buffer[(ptr+i)%channelWidth+c*channelWidth] * windowFFT[i]);
            inFFT[i].i = 0;
        }
```

this is copying samples across, what if we were to accumulate the samples in a buffer of type `ne10_float32_t*` already?

inFFT[i].i is always going to be zero, if I am not wrong, so this could be just initialized once ?

Solving all the issues above would probably be possible (and probably faster) by using a real-to-complex fft instead (as the input signal is always going to be real).

```
                    float mag = (float)(outFFT[j].r * outFFT[j].r + outFFT[j].i * outFFT[j].i);
```

If magnitudes were computed with an optimized function, then it would probably help computing them all at once.
There does not seem to be an appropriate "complex magnitude" function in NE10, but some of the vector multiplication ones should help.

```
            for (int i=0; i<frameWidth; i++){
...
                } else if (FFTXAxis == 1){  // logarithmic
                    findex = expf((float)i*logConst)*ratio;
                }
...
            }
```

this is constant for a given ratio and should be cached

Use of math-neon approximations for log and expf throughout is probably alright.

**Comment by giuliomoro** [comment]
also it looks like there is a memory leak as `inFFT` / `outFFT` are only allocated but never freed?

**Comment by LBDonovan** [comment]
Huh. We definitely used to free them, but it does appear that we don't anymore

**Comment by giuliomoro** [comment]
```
                    float mag = (float)(outFFT[j].r * outFFT[j].r + outFFT[j].i * outFFT[j].i);
```
turning this into
```
ne10_float32_t* srcdst = (ne10_float32_t*)outFFT;
ne10_mul_float_neon(srcdst, srcdst, srcdst, FFTLength * 2);
...
float mag = outFFT[j].r + outFFT[j].i;
```
yields less than 0.5% CPU saving (1024/linear/normalised)

**Comment by giuliomoro** [comment]
caching `findex` gets rid of the ~5% CPU increase when using logarithmic X axis

**Comment by LBDonovan** [comment]
Nice

**Comment by giuliomoro** [comment]
getting rid of `inFFT[i].i = 0;` saves about 0.3% CPU. 

The indexing
```
[(ptr+i)%channelWidth+c*channelWidth]
```
is too expensive, too ( I believe about 1% CPU) . Again, this should be fixed by accumulating into a `ne10_float32_t*` buffer and avoiding the copy and running a real to complex fft.

**Comment by giuliomoro** [comment]
did most of the supposed optimizations. It seems they do not yield large improvements (if any at all). I "blame" this on clang being very good at generating NEON code

**Comment by giuliomoro** [comment]
is it worth it giving a shot at WebAudio API's FFT to offload it from Bela to the browser?
It must be the following:
```
    var analyser = audioContext.createAnalyser();
    analyser.getFloatFrequencyData(out)
```
see, e.g.: [here](https://github.com/Matt-Esch/browser-fft/blob/master/index.js)

**Comment by LBDonovan** [comment]
I would say this is a lower priority than a web socket server or shared memory interface, as it will take a lot of work and have a much smaller effect on the core scope usage.

It might be worth a try, though I'm skeptical about performance and would worry about people not being able to run it on slightly older laptops or browsers.

**Comment by giuliomoro** [comment]
@LBDonovan you have some work on this. Anything worth sharing, especially if it could be helpful towards https://github.com/BelaPlatform/Bela/issues/71

**Comment by giuliomoro** [comment]
Performance has improved. Bigger fish to fry these days. I'd offload FFT to browser, but that's for another issue, e.g.: #401
