### ISSUE TITLE
drag and drop not very well supported across browsers

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#12]
if possible it should be fixed, if it is not, then a traditional html4 upload button should be provided as a fallback ( current  upload file button is reported not working on those same browsers where the drag and drop does not work)

**Comment by LBDonovan** [comment]
@giuliomoro can you tell me which browsers (including version number) and operating systems?

**Comment by giuliomoro** [comment]
Older versions of chrome (50) and safari (unknown) on mac. Sorry don't have more details
