### ISSUE TITLE
IDE scope offset should allow to move around when the scope is paused

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#122]
e.g.: after a normal trigger or a single-shot

**Comment by LBDonovan** [comment]
This would be trivial for the y-axis offset, but impractical for the x-axis, as it would either require a lot more data to be sent from the scope to the browser every trigger (which would massively negatively impact performance) or for the scope to save that data in a buffer in the c++ code and send it across when asked, which would also negative impact performance and memory usage, and take a lot of effort to code. The same thing goes for zooming the x axis when paused (zooming out, at least).

**Comment by giuliomoro** [comment]
Ok this is duplicated of #119
