### ISSUE TITLE
IDE Scope GUI remarks

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#123]
- [x] the x-y position cursors readings should be displayed even when the overlay controls are on

- [ ] The overlay is too invasive once you are done with it. It'd be good if it would go semi-transparent automatically after one second of inactivity.

- [ ] currently when on one-shot and auto trigger, it stops immediately (with the first auto-trigger), whereas it should keep auto-triggering until the first "normal" trigger comes in

- [ ] the one-shot / resume / pause buttons should have more obvious colour changes (Keysight scopes use Yellow when one-shot is loaded, red when paused and green when running (auto or normal).

- [x] simple keyboard shortcuts for easy operation would be great. Gather your suggestions here.

- [ ] the background should not go gray when in single shot or normal trigger mode, despite what I requested elsewhere (didn't know what I was talking about, forgive me !). I guess we need a "keep-alive" ping from the Bela program to the browser page

**Comment by LBDonovan** [comment]
> the x-y position cursors readings should be displayed even when the overlay controls are on

yes

> The overlay is too invasive once you are done with it. It'd be good if it would go semi-transparent automatically after one second of inactivity.

Agreed, I'm hoping @disastrid will have a quick go at the scope UI when she gets a chance (no rush!), including doing something to hide the overlay when it's not being used.

> currently when on one-shot and auto trigger, it stops immediately (with the first auto-trigger), whereas it should keep auto-triggering until the first "normal" trigger comes in

That sounds like expected behaviour to me. Do hardware scopes not count auto triggers in one-shot mode? Maybe activating one-shot mode should automatically switch the trigger from auto to normal.

> the one-shot / resume / pause buttons should have more obvious colour changes

Agreed

> simple keyboard shortcuts for easy operation would be great

I would be happy to implement them, but what would they be/do?

> The background should not go gray when in single shot or normal trigger mode

Agreed

**Comment by giuliomoro** [comment]
most of these things are outdated, or have been fixed (e.g.: press ESC to toggle visibility of controls), the behaviour of single-shot is probably right ... closing, as things have changed and new issues should be opened against the current state of the scope.
