### ISSUE TITLE
analogWrite should write all of the successive frames unconditionally

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#125]
It currently checks if BELA_FLAG_ANALOG_OUTPUTS_PERSIST is set before writing till the end of buffer, which means there is a branching every time you write:

```
// analogWrite()
//
// Sets a given analog output channel to a value for the current frame and, if persistent outputs are
// enabled, for all subsequent frames
static inline void analogWrite(BelaContext *context, int frame, int channel, float value) {
    if(context->flags & BELA_FLAG_ANALOG_OUTPUTS_PERSIST) {
        for(unsigned int f = frame; f < context->analogFrames; f++)
            context->analogOut[frame * context->analogOutChannels + channel] = value;
    }
    else
        context->analogOut[frame * context->analogOutChannels + channel] = value;
}
```

now, this is not necessarily very bad, as `analogWrite()` is not supposed to be called for every sample, but once or less every buffer. Yet, it may be confusing because `digitalWrite` does not behave the same (i.e.: writing to the end of the buffer is unconditional).

In the current implementation, when `BELA_FLAG_ANALOG_OUTPUTS_PERSIST` is not set, `analogWrite` basically decays to `analogWriteOnce`.
I believe the rationale behind this was that if `BELA_FLAG_ANALOG_OUTPUTS_PERSIST` is not set, then outputs would not persist across buffers, therefore writing to the end of buffer would not make much sense, as the next buffer would not be init'ed to that same value.

I advise we make this unconditional and users are advised against using `analogWrite()` altogether when `BELA_FLAG_ANALOG_OUTPUTS_PERSIST` is not set

**Comment by apmcpherson** [comment]
Sure, maybe we should just make the same recommendation for digital and abandon this flag entirely. Alternatively it could become a compile-time option, but for various reasons I think we decided against that, and anyone expert enough to want to do that can probably just update their code to use `analogWriteOnce()`. The question is how much CPU we save by not copying the last analog value to each frame in the next buffer.
