### ISSUE TITLE
IDE should preserve file permissions of uploaded files

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#126]
... so you can drag and drop executables and execute them.
If this does not work, then I'd suggest if the file is recognized as binary, then its permissions should be set to 744 (executable).

**Comment by giuliomoro** [comment]
This would allow binaries to be drag-and-dropped on the IDE and executed

**Comment by LBDonovan** [comment]
Is this for Faust?

If the structure of a Faust project is different (i.e. just a binary?) it might be worth considering having an extra option in the new project dialog that expects the right structure.

Permissions can't be read by browsers btw (I think) so they will have to be set specifically.

**Comment by giuliomoro** [comment]
Yes it would be good for Faust or for anyone willing to drag and drop a file and execute it.
Surely good to support this natively, but the the two features are needed for a wider use case than just Faust:
- show hidden files (so you can have control on your folder)
- preserve permission (so if you drag and drop any script/binary you can then execute from the terminal without chmod-ding it). I suspected browsers couldn't read permissions. That's lame :(

**Comment by LBDonovan** [comment]
It would be nice if the Makefile executed the binary, so you could use the run button to run the executable. Do the Faust binaries have a consistent name, or some other way of identifying them?

But yes, the other stuff about permissions and hidden files all makes sense.

**Comment by giuliomoro** [comment]
You mean the Makefile makes the file executable before running it?
Good point, that would work, I suppose.
