### ISSUE TITLE
IDE console error message line number is off by 1

### ISSUE THREAD

**Issue by pinheadmz** [BelaPlatform/Bela#129]
https://github.com/BelaPlatform/Bela/blob/5d0269aad6243549038352d49488b54cc3f5e5e2/ide/IDE/public/js/src/console.js#L76

Should that value be `err.row+1` like it is in lines 81 & 83?

![screen shot 2016-09-19 at 5 34 40 pm](https://cloud.githubusercontent.com/assets/2084648/18653537/65a90ed8-7e8f-11e6-85a4-d10eed0ec6e9.png)

**Comment by LBDonovan** [comment]
Yes I think you're right, thanks! I'm surprised nobody spotted that before.

**Comment by giuliomoro** [comment]
a good excuse not to have spotted it it is that when you click on the message it takes you to the correct line
