### ISSUE TITLE
Wiki page refers to incorrect IP address

### ISSUE THREAD

**Issue by gareth8118** [BelaPlatform/Bela#13]
In the first paragraph of the [IDE Wiki page](https://github.com/BelaPlatform/Bela/wiki/Bela-IDE), there is a reference to http://192.178.6.2/ - I think this is a transposition error and should read http://192.168.7.2/ as reflected in the screenshot directly below it.

**Comment by disastrid** [comment]
Thanks so much for spotting this Gareth! It’s been amended. :)

Astrid.

--
S. Astrid Bin
PhD Researcher, Media and Art Technology
Centre for Digital Music
Queen Mary University of London
a.bin@qmul.ac.uk

**Comment by gareth8118** [comment]
Hi @disastrid - one more change needed before close - it's now http://192.178.7.2/ - the second octet still needs to change to "168".

**Comment by disastrid** [comment]
Hi Gareth,

As we gallop towards release I really appreciate another pair of eagle eyes. :) Thanks so much, should be correct now!

A.

--
S. Astrid Bin
PhD Researcher, Media and Art Technology
Centre for Digital Music
Queen Mary University of London
a.bin@qmul.ac.uk

**Comment by giuliomoro** [comment]
Thanks @gareth8118 . I now made the wiki pages editable by anyone
