### ISSUE TITLE
update script should not change current project in the IDE

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#130]
I find it pretty annoying, don't you ?

**Comment by LBDonovan** [comment]
Tbh I very rarely use the update script (I usually use gulp to upload stuff, and the IDE to edit the core) so it's never bothered me!

If you want this to stop happening just prevent `IDE/libs/settings.json` from being deleted by rsync. Not a good idea to do this in general though, as if the settings.json is wrong, the IDE may not start properly.

**Comment by giuliomoro** [comment]
ok, I see your point . Won't fix
