### ISSUE TITLE
Bypass node in scope raw-data streaming

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#131]
That is, run a websocket server within Bela, this should help https://github.com/zaphoyd/websocketpp/

I reckon this will help us save lots of CPU, as currently node goes up to some 30% CPU and it is just relaying OSC messages containing binary data from the Bela program to the browser.

I suggest the scope keeps two separate websocket connections, one to the IDE for configuration/controls (so to allow easier filtering/scaling/mapping/stuff) and one to the Bela program for the raw data (to make it faster).

**Comment by LBDonovan** [comment]
Yes I have tried to do this several times, but the c++ websocket libraries are tricky. I could not get it to work, from what I remember it seemed to require boost, even though it seems to say it doesn't necessarily. I found the examples in that library you linked hard to interpret.

At the moment the data is sent over raw UDP to node, not OSC, but it's definitely the biggest drag on CPU. Another idea I've been meaning to try is to write a shared memory interface to transfer the data over to node, as that would save a lot of CPU, but would require compiling an add-on. Though this wouldn't be as good for the scope as doing native web sockets in Bela, I think it would be a more flexible way of transferring data in general.

If you can get a websocket server running in Bela, I will happily join it up with the browser!

**Comment by giuliomoro** [comment]
You are very right, after posting this I tried this library and two more but all of of them have extra dependencies . Pretty annoying, though we could just install the dependencies and be happy with that.
 Also good point about the shared memory. 
Will see what I can do

**Comment by giuliomoro** [comment]
http://www.xenomai.org/pipermail/xenomai/2015-June/034406.html

**Comment by giuliomoro** [comment]
pipes: https://github.com/giuliomoro/xenomai-node-pipe

**Comment by giuliomoro** [comment]
closed at some point!
