### ISSUE TITLE
IDE add overlay warning that Pd patch is only a preview 

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#132]
Some users would expect GUI objects (e.g. number boxes, sliders) in there to be updated by their program.
We should warn them:

"This is just a preview. GUI objects will not be updated and you cannot interact with it in real-time (yet)."

**Comment by giuliomoro** [comment]
also add it to the wiki

**Comment by giuliomoro** [comment]
note for later: "... or make them interactive". This was achieved by e.g.: PdParty on Android:

> PdParty then uses libpd and a custom UI which communicates with the libpd instance and any patches currently loaded.

and there should be a paper on the topic coming out at Pd Con 2016 this month.

https://lists.puredata.info/pipermail/pd-list/2016-09/116417.html

**Comment by LBDonovan** [comment]
Yeah this would be relatively easy to do as the infrastructure is all there with the scope-sliders etc. There's just no time!

**Comment by LBDonovan** [comment]
I've added it to a console message rather than as a popup because it's less intrusive. Still needs to be added to the wiki.
