### ISSUE TITLE
IDE: add support for audio expander (dev-capelet branch)

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#139]
Two new command-line options have been added to the dev-capelet branch. Support should be added in the IDE (maybe a set of tick boxes for each channel).

-Y or --audio-expander-inputs enables specific channels for audio input using the audio expander; -Z or --audio-expander-outputs enables specific channels for audio output. Arguments are comma-separated lists of numbers. See here for details:

https://github.com/BelaPlatform/Bela/wiki/Using-the-Audio-Expander-Capelet

**Comment by giuliomoro** [comment]
It may be working (not sure what it is supposed to do), but every time I stop a program (regardless of whether is run from the `projects/` or `examples/` folder), I get this warning on the console:
```
Warning: invalid audio expander input channels '-Z'-- ignoring
```

**Comment by LBDonovan** [comment]
This probably happens when no output channels are activated and the '-Z' flag is passed with no arguments. Would it be possible to just get rid of the warning from the core code in that case?

**Comment by apmcpherson** [comment]
-Z with no arguments would be malformed as a command-line argument, so it would be better for the IDE not to generate this at all if no channels are enabled.

**Comment by giuliomoro** [comment]
Tested, confirmed
