### ISSUE TITLE
Add support for pasm / pru C compiler to the Makefile

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#142]
https://github.com/BelaPlatform/bela-image/issues/5

**Comment by giuliomoro** [comment]
Alright, done this, I tried to keep the same folder structure as the current second-pru example.

This has a few drawbacks:
* `pasm` will run during syntax check. This is because it is listed to generated the `%_bin.h` file, which is needed by `render.cpp`, but in case of error during syntax check, this is not reported by the syntax checker indicator NOR displayed to the user.
* the `%_bin.h` file is updated continuously as you edit the `%.p` file. This may cause weird behaviour when you have both open (why should you?)

solutions?

* hack the Makefile so that it does not run this in case of `syntax`
* do not use a `%_bin.h` file, but a `.bin` one. This will remove it from the dependencies of `render.cpp` and will be loaded at runtime, so you do not even need to recompile the `.cpp` file for changes to the `.p` file. Drawback: the `.bin` file is less git-friendly than the `.h` one.

(Note that `pasm` is VERY fast)

**Comment by LBDonovan** [comment]
Why are the errors not reported during syntax check? Are they reported by the Makefile but ignored by the IDE or are they not generated at all?

Honestly it sounds like the .bin file output gives a better workflow, we could even .gitignore it as all the information is in the .p file.

**Comment by giuliomoro** [comment]
The pasm process exits with 1 upon errors.

The reason why they are not reported may be that they are not output to `stderr` ?

In fact, when you build, they are showing as regular text and not in a yellow/red background.

**Comment by giuliomoro** [comment]
I could edit `pasm` and make it print errors to stderr instead.

**Comment by giuliomoro** [comment]
Done https://github.com/giuliomoro/am335x_pru_package/commit/a02f92a7b1d15663e7639978432703531fade148

Still, these errors are not picked up by the syntax checker, despite `pasm` exits with non-zero error code, it is writing to `stder` and the syntax is being checked (I see the syntax checker flicker).

So I edited `libs/ProcessManager.js` so that it does `console.log(status)` in `syntaxCheckProcess.on('finished', (data) =>` 
and this is what I get for an error in the pru code:
```
{ checkingSyntax: false,
  building: false,
  buildProject: '',
  running: false,
  runProject: '',
  syntaxError: 'pru_gpio.p(18) Error: Invalid opcode\nmake[1]: *** [/root/Bela/projects/exampleTempProject/pru_gpio_bin.h] Error 1\n' }
```

And this when I fix the above error and there is an error in the cpp code:
```
{ checkingSyntax: false,
  building: false,
  buildProject: '',
  running: false,
  runProject: '',
  syntaxError: '/root/Bela/projects/exampleTempProject/render.cpp:30:1: error: unknown type name \'scsdc\'\nscsdc\n^\n/root/Bela/projects/exampleTempProject/render.cpp:35:9: error: expected \';\' after top level declarator\nuint32_t *gPRUCommunicationMem = 0;\n        ^\n        ;\n/root/Bela/projects/exampleTempProject/render.cpp:161:2: error: use of undeclared identifier \'gPRUCommunicationMem\'\n        gPRUCommunicationMem = &pruMemInt[0x800/sizeof(uint32_t)];\n        ^\n/root/Bela/projects/exampleTempProject/render.cpp:187:2: error: use of undeclared identifier \'gPRUCommunicationMem\'\n        gPRUCommunicationMem[PRU_COMM_USER_DELAY] = (uint32_t)delay;\n        ^\n4 errors generated.\nmake[1]: *** [/root/Bela/projects/exampleTempProject/build/render.o] Error 1\n' }
```

Yet, the first one will make the syntax checker green and only the second one will make it red.
