### ISSUE TITLE
IDE: warnings all show up at the end instead of during compilation

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#152]
Say you are compiling some code which has warnings (say unsigned signed comparison), these warnings will be logged to the console only at the end of the build process.

Is this expected?

**Comment by LBDonovan** [comment]
Is that on the latest build? I thought I had fixed this in 2a6e4ad.

Are these compiler warnings or runtime stderr output? If they're compiler warnings something is definitely amiss.

**Comment by giuliomoro** [comment]
Compiler warnings. To reproduce:

- clean project
- `git checkout 1aaca799a33d12e48feda512d5f536410c980289 core/RTAudioCommandLine.cpp` and copy that file to the board
- in the IDE, set makefile flags to  `COMPILER=gcc` (because gcc complains about this, while clang does not
- hit "build".

**Comment by LBDonovan** [comment]
Is the error in the core code?

This probably happens because we disabled syntax checking for the core. I don't really know why we did that, I actually quite liked it when we had it on.

**Comment by giuliomoro** [comment]
It also happens for project code. Get an example and remove the `unsigned` from the `unsigned int` iterators, set the makefile flag to `COMPILER=gcc` and compiler. You will see the compiler warnings showing up after the linker and before the `running project`

A good reason to disable syntax checking on the core code is that it would take up more resources and is not needed 99% of the time.

**Comment by LBDonovan** [comment]
I can't reproduce this, I get the warnings with the syntax check. You might need to edit the code to force a syntax check immediately after inputting the make parameter.

**Comment by giuliomoro** [comment]
I will show you. let's forget about this for now.
