### ISSUE TITLE
core: numAnalogInputChannels should be allowed to be 0

### ISSUE THREAD

**Issue by sensestage** [BelaPlatform/Bela#160]
If useAnalog = 0, then the number of analog channels should also be allowed to be 0.

See also: https://github.com/sensestage/supercollider/issues/22

**Comment by giuliomoro** [comment]
By the looks of it, it was done some time ago. Not sure when/how/where, but now if you disable analogs, you get what you expect: `analogFrames=0`, `analogInChannels=0`, `analogOutChannels=0`, `analogSampleRate=0`
