### ISSUE TITLE
BeagleRT program stops running/LED stops blinking/audio stops when touching big USB socket

### ISSUE THREAD

**Issue by dianneverdonk** [BelaPlatform/Bela#165]
I made a metal case around Bela, but when the case contacts the big USB power socket, loud ticks in audio appear and the program stops running soon (while running bela standalone)/BeagleRT led stops blinking/audio stops. Seems like something short cirquits, but the socket is only a ground, isn't it? Does anyone know why I should avoid this (other than it stops Bela from running)? Thanks a lot!

**Comment by giuliomoro** [comment]
Hi Dianne, 
what you describe sounds like shorting one of the power supplies to ground. 

The external part of the USB connector should be grounded, so it probably means your case is touching 3.3V or 5V? Also, the bottom of the board should be insulated from the metallic enclosure, and the case should not touch any of the pins on top of the board.

A better place for this question is probably the [forum](http://forum.bela.io), although to post pictures there you will have to upload them somewhere and post a link (e.g.: imgur works great).
Make sure you include pictures of your setup, detailing which wires go in and out the board.
