### ISSUE TITLE
Muxer capelet does not seem to be working properly

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#166]
Is there need to place a dtbo or dtb file somewhere? I see no changes were made to the `resources/` folder in `dev-capelet.

If I understand how the muxer works, this code should be printing at any time the analog inputs from the muxer (with the muxer set to 8 channels):

				for(int firstAn = 4; firstAn >= 0; firstAn -= 4){
					for(int firstMux = 1; firstMux >= 0; --firstMux){
						for(int an = firstAn; an < firstAn + 4; ++an){
							for(int mux = firstMux; mux < 8; mux += 2){
								rt_printf("%.3f, ", multiplexerAnalogRead(context, an, mux));
							}
						}
						rt_printf("\n");
					}
				}

I am going around with the 3.3V from P9_3 , touching the various pins, but at least half of them don't work, in a strange pattern ...

**Comment by apmcpherson** [comment]
Check that the `resources/initd-bela` script has been copied to the image under `/etc/init.d/bela`. There is indeed a new dtbo file (BB-BONE-PRU-BELA) which replaces the system-standard BB-BONE-PRU dtbo which was loaded in the original image; it enables P8.41 to P8.46 as PRU pins. But the new script is needed to load the custom dtbo, and will need to be manually copied to the image.

**Comment by giuliomoro** [comment]
Actually it was none of the above.
It was something much more stupid.
I got confused and I was not using P9_3, but P8_44, if you know what I mean :).
