### ISSUE TITLE
Scope: when toggling FFT/time domain sliders position should match numerical value

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#172]

**Comment by LBDonovan** [comment]
Can you give me an example of where this is a problem? I'm not sure I quite understand what you mean...

**Comment by giuliomoro** [comment]
when you switch from time-domain to fft, the amplitude and scaling values are changed to 70 and 69. But the position of the associate slider is not changed, so that the position of the slider turns out to be out of sync with what the number in the number box is.

**Comment by LBDonovan** [comment]
Right, gotcha. Should be an easy fix...
