### ISSUE TITLE
Create Xenomai-compatible class for passing messages between real-time and non-realtime threads

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#174]
Basically a wrapper around `rt_pipe` which takes care of creating the pipe and opening the pseudo-filedescriptor.

https://github.com/BelaPlatform/Bela/blob/dev-midi/core/Midi.cpp

This could then be used by Scope / Bela_I2c / WriteFile / Midi

**Comment by LBDonovan** [comment]
+1 this would be great

**Comment by giuliomoro** [comment]
this may require - as part of this or in a separate class - a "filedescriptor-to-pipe", similar to what you would obtain with
`cat /dev/midi1 | /proc/xenomai/registry/native/pipes/pipename`
and 
`cat /proc/xenomai/registry/native/pipes/pipename | cat /dev/midi1`
which is basically what happens the whole time in auxiliary tasks loops.

**Comment by giuliomoro** [comment]
Done the Xenomai - side class here: https://github.com/giuliomoro/xenomai-node-pipe

**Comment by giuliomoro** [comment]
done at some point in the past: it's in `libraries/Pipe/`
