### ISSUE TITLE
IDE: force refresh after updating board ...

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#193]
... or strange things may happen

**Comment by LBDonovan** [comment]
So as of fa4c986 this should happen automatically. However it will only happen if the old version which is being updated has that commit on the board, because it is still the old version of the code which is running in the browser, even after the update has finished.

**Comment by giuliomoro** [comment]
fair enough

**Comment by LBDonovan** [comment]
We may want to test that it works though, with the newest version. I have a feeling I never did.
