### ISSUE TITLE
Pd: add scope custom triggers

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#21]
E.g.: sending a trigger to last scope channel + 1 (so we need to add one more dac~ )

**Comment by giuliomoro** [comment]
Actually, it occurs to me that using an additional [dac~] channel for triggering would be complicated.
What if instead of calling `bool Scope::trigger()`, the user simply sends the trigger signal (that is all zeros with a one when the trigger should occur) out to a channel `x` and then they set trigger mode to `normal` and trigger channel to `x` ?
@LBDonovan, would this achieve the desired result ?

**Comment by LBDonovan** [comment]
Yes that would work. People would have to manually set the trigger channel correctly though, and you would be able to see the trigger signal, at least by default. I guess you could maybe write some code that hides this from the user.

**Comment by giuliomoro** [comment]
Not needed: you can trigger "custom" from another channel
