### ISSUE TITLE
IDE: Error with rendering of Pd projects when resizing console bar with project open

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#213]
Open the gettingstarted Pd example.

Move the console window so that it is smaller. You'll see that the Pd patch is not rendered underneath where the console window used to be.

**Comment by giuliomoro** [comment]
Same for images being previewed. Also same when you close the side tab

**Comment by giuliomoro** [comment]
this was fixed for Pd and f89cf0e9 does it for images, too.
