### ISSUE TITLE
`-no-integrated-as` should be excluded for gcc

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#216]

**Comment by djzielin** [comment]
I just got error message / issue when trying to build after a recent update. How do I move forward?

Building math_runfast.c...gcc: error: unrecognized command line option '-no-integrated-as'make: *** [build/core/math_runfast.o] Error 1

**Comment by djzielin** [comment]
Hmm, I just removed that item from the Makefile and it now seems to be building and running okay.

**Comment by giuliomoro** [comment]
Hmm this means you are building with gcc. Did you do that on purpose? This was the default in older images because of a bug in the IDE startup script, are you forcing gcc or is it just your default? Clang is recommended because it generates faster code

**Comment by djzielin** [comment]
Oh, it seems clang is not installed on my beaglebone? I'm apt-get'ing it now.

**Comment by giuliomoro** [comment]
Oh that's quite funny.
`clang` 3.8 should be on the board, though it will not show up with `dpkg -l` because the ARM binaries provided by llvm were installed manually in `/usr/local/bin`. Also, `apt-get` will think it is not there.
On an early version of the board, the IDE would not use `clang` by default, because the environment variables were not initialized appropriately (`$PATH` did not include `/usr/local/bin`), but this has been fixed like 6 months ago, so it should not be the case as you mentioned you updated recently.

How can you tell `clang` was not on your board? The console at the bottom of the IDE has the same PATH environment as the IDE, so if the IDE cannot find `clang`, not even the built-in console  will. The actual way to test if `clang` is on the board is to run `/usr/local/bin/clang`.

Also, I am not sure what version of `clang` you get with `apt-get`: versions before 3.5 had some troubles with heavy-generated code.

**Comment by djzielin** [comment]
Yeah, the apt-get installed clang 3.5
I checked /usr/local/bin/clang and its 3.8

Perhaps this is the telling part:
If I ssh in, and I echo $PATH /usr/local/bin shows up
If I do that (echo $PATH) inside the IDE /usr/local/bin is not in the list.
Hmmm.

P.S. Are there updates I should run aside from updating the bela core via
the browser? apt-get upgrade? I haven't done anything but the browser based
updates because I don't want to break anything.

Best,
-Dave

**Comment by giuliomoro** [comment]
given that the IDE is started at boot, the default PATH is minimal and the launch script should be setting it appropriately. 
This is done in `/root/Bela_node.sh`, where you should be a few commands:

`export USER=root && export HOME=/root && export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

Now, I expected that this file would be re-generated at every update through the IDE, but I just checked the `Makefile` and - as it turns out - it is not quite the case, so your `/root/Bela_node.sh` will probably not have the above commands.
to fix this you must manually run the following, it should work from the console at the bottom of the IDE:
```
make -C /root/Bela idestart
```
then try a reboot and then type in the console 
```
$ clang --version
```
it should return
```
clang version 3.8.0 (tags/RELEASE_380/final)
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by djzielin** [comment]
okay its actually

make -C /root/Bela idestartup

**Comment by giuliomoro** [comment]
Yes correct, sorry
