### ISSUE TITLE
Board disconnecting when Bela CPU is too high

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#222]
I'm running a pd patch that is pushing Bela to its CPU limits (80%+). The IDE keeps on losing connection with the board, for example when I press stop the patch keeps on running but I get disconnected from the board and have to unplug. Perhaps a warning message would be a good idea when people are in similar situations. "The project you are trying to run is too CPU intensive to run on Bela, try and strip down your code or expect erratic behaviour". 

Unless you think this is caused by something else. Attached files that are causing the problem in case you're interested.

[benedict_XVI 2.zip](https://github.com/BelaPlatform/Bela/files/663334/benedict_XVI.2.zip)

**Comment by LBDonovan** [comment]
Hmm, I tried but could not reproduce the issue. Usually when this happens it is a problem with the USB cable or socket on the host rather than a software issue, is that possible here?

**Comment by roberthjack** [comment]
I think you're right, I tried to reproduce this again I couldn't although it was consistently disconnecting before with the heavy load projects. Must have been a coincidence. Will let you know if I can identify it more precisely later. Cheers!
