### ISSUE TITLE
What should `xxxFrames` and `xxxYyyChannels` and `xxxSampleRate` set to when xxx is disabled?

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#238]
Where `xxx` is `analog` or `digital`.

An easy choice would be to have everything set to 0, but I see how this could cause issues (e.g.: if you are computing the `1/SampleRate` or `digitalFrames/analogFrames`)

I think it makes sense to keep `SampleRate`and `Frames` to a default value (e.g.: same as audio) while setting Channels to 0.

@apmcpherson @LBDonovan opinions?

**Comment by giuliomoro** [comment]
Also see #160.

**Comment by apmcpherson** [comment]
I think frames should be 0 when disabled. The most common use case, by far more common than sample rate calculations, is a `for` loop going over the number of frames. Set the frames to 0 and it automatically skips over it. The number of channels can also be set to 0.

**Comment by giuliomoro** [comment]
what about `SampleRate`? should it be 44100 or 0 ?

**Comment by giuliomoro** [comment]
The recent update in examples in `dev-examples` now correctly handles the cases where any of these properties are 0.
