### ISSUE TITLE
USB device not always recognized (hotplug issue)

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#24]
see here
http://forum.bela.io/d/29-midi-interface/8

here
https://groups.google.com/forum/?fromgroups#!searchin/beagleboard/usb/beagleboard/8aalvyWwaig/MUXAPuMTSOYJ

and here
https://groups.google.com/forum/?fromgroups#!category-topic/beagleboard/beaglebone-black/nuyyVDhU6bw

and try this 
`echo on > /sys/devices/ocp.3/47400000.usb/power/control`

If it works, hotfixes are:
- add button in the IDE for USB reset
- add script for USB reset 
- add command-line option for the Bela script to perform USB reset when the program starts ( could be useful for headless operation ). Maybe combined with an added "restart program" functionality for the Bela button.

real fix is patching the kernel.

**Comment by LBDonovan** [comment]
+1 for patching the kernel.

i think this might be the fix:

https://github.com/beagleboard/kernel/commit/35a3abaaa7a44cdec3e4c63407b48d7cdc2a8533

**Comment by giuliomoro** [comment]
thanks I had found a broken link to the same and could not find the working one.
Patching the kernel will require a long testing period. In the meantime I will add a script to do this. IDE users can use the built-in shell to do it :)

**Comment by giuliomoro** [comment]
actually I believe that patch is already in the current image but there are a number of USB-related patches available in 3.8.13-bone67-xenomai that are not in the version currently on the board (47) :(

**Comment by giuliomoro** [comment]
and, the proposed fix
```
echo on > /sys/devices/ocp.3/47400000.usb/power/control
```

did not work for me

**Comment by giuliomoro** [comment]
I updated my kernel to  3.8.13-bone67-xenomai and this did not fix the hotplug issue, despite this revision contains the patch mentioned above.

**Comment by giuliomoro** [comment]
Actually, this worked after a couple of trials and errors:
```
cd /sys/bus/usb/drivers/hub
echo 1-0:1.0 > unbind
echo 1-0:1.0 > bind
```
this would power on the device, but I had to unplug and replug it in order to have it show up with
```
lsusb
```
so not working 100%, but could come in handy

**Comment by giuliomoro** [comment]
won't fix. Blame it on 3.8.13. Works like a charm on 4.4
