### ISSUE TITLE
IDE: should check for return code of `make checkupdate` and `make update` instead of monitoring `stderr`

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#242]
A user reported a fail as follows: https://forum.bela.io/d/59-sigmund/18
```
Validating archive...
uncompressed size: 
28878473Unzipping archive...
Validating unzipped archive...
...done
Error updating the board, please try a different zip archive
```
So it seems that `make checkupdate` was successful (as denoted by "`Validating unzipped archive...done`", but then why does the IDE throw "`Error updating the board, please try a different zip archive`" ?

An earlier users reported a different error "not a valid update archive" https://forum.bela.io/d/209-midi-clock-with-libpd/5

**Comment by LBDonovan** [comment]
It looks like this would happen if 'make checkupdate' or 'make update' put anything out of their stderr, which they presumably didn't used to do? Has that changed? It would probably be better not to abort everything if something happens on stderr...

**Comment by giuliomoro** [comment]
I don't know why they would put something into stderr. It would be easier and safer if we could check for the return code of `make`: it returns non-zero if an error occurs.

**Comment by giuliomoro** [comment]
In 1f8d878 I mistakenly added a line to the `Makefile` which causes`Makefile: 131: yes` to go to the `stderr` during the update process. Maybe that is what triggered these failed updates. I removed that line in 6571bcbca98e15afc865c1c651c3b330a801acbb, but this means the boards which have been updated in that period will have to manually update: 
```
make -C /root/Bela checkupdate && make -C /root/Bela update
```

**Comment by giuliomoro** [comment]
This got me once more.
@LBDonovan This is urgent.

**Comment by giuliomoro** [comment]
thanks
