### ISSUE TITLE
IDE: "download project" button

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#244]
Currently you can download one file at a time or all the projects at once, but I see no way to download a single project as a zip archive.

**Comment by amilo** [comment]
In my experience, if you open a project, you can download the single project through the download button (down arrow icon, fourth from left on the bottom bar).
What I couldn't find, instead, is a way to upload entire projects from disk to the board.

**Comment by giuliomoro** [comment]
Well spotted. Maybe the GUI redesign wants to make that more obvious?
Closed.

to upload an entire project, just drag and drop multiple files at once, or press "upload file" and select multiple files. You cannot drag and drop folders at the moment.
