### ISSUE TITLE
"IDE": missing UPLOAD project 

### ISSUE THREAD

**Issue by amilo** [BelaPlatform/Bela#245]
Is there a way to upload an entire project to the board (as a zip folder which will be extracted for example)?

I can only upload single files to an existing project. I can also copy projects and edit them, but I fould difficult to do live edits in the code this way since whenever you change the render.cpp the board prompts "keep current file" or "use file from disk", and I am not sure how I can save changes when I want (or if this is done in automatic).

I suppose I can scp my project folder from terminal. Where can I find the relevant information?

**Comment by giuliomoro** [comment]
If you see this error it may be that you have multiple IDE tabs open at the same time.Make sure you only have one tab open at a time with the file you are editing ( though it should be safe to have different files in different tabs ).

**Comment by amilo** [comment]
@giuliomoro, if you create a new projects and you drag inside your files, the board complains and doesn't copy all the files. Also, there are issues regarding overwriting hidden (if actually copied) and duplicate project files (which may not be important if you didn't change settings, otherwise you may miss important information, since the IDE will ask if you want to overwrite them). Anyway this may lead to the interruption of the copy process.

**Comment by amilo** [comment]
@giuliomoro the only tab open on the IDE was the documentation. Could accessing these files in a separate tab in the browser affect the drag and drop/copy in another tab?

**Comment by giuliomoro** [comment]
if you drag-drop files in tab1 and you overwrite an existing file that is open in tab2, when you go back to tab2 it will ask you whether you want to keep the file as it is currently displayed (old version) or reload it from disk (that is: load the file you just uploaded to the board).
The documentation tab (as in : 192.168.7.2/documentation ) will not affect this behaviour.
If something else happens, then that is a bug.

Hidden files are copied only if you select them from the source folder. You can show hidden files in the IDE by selecting "view hidden files" from the configuration panel of the IDE.

Why does your workflow require to often drag and drop files to the IDE? Could you not edit them directly within the IDE?

**Comment by LBDonovan** [comment]
If you are getting a pop-up informing you that the file has changed on disk when you are editing a `.cpp` file, it's likely you are on an old version of the code (or there is a big bug). That 'feature' was removed a while ago for everything except `.pd` files because it was so buggy.

Could you check what version of the code you are using (settings tab -> 'About Bela' at the bottom). You might need to [update](https://github.com/BelaPlatform/Bela/wiki/Updating%20Bela).

There will be an `upload project` button at some point, its just slightly more complicated than uploading individual files and I haven't quite got round to it :)

**Comment by LBDonovan** [comment]
> if you drag-drop files in tab1 and you overwrite an existing file that is open in tab2, when you go back to tab2 it will ask you whether you want to keep the file as it is currently displayed (old version) or reload it from disk (that is: load the file you just uploaded to the board).

This is wrong btw, if you edit code in one tab and it is open in another, the other tab will be frozen, there should be no popups and it should work fine.

**Comment by amilo** [comment]
@LBDonovan I am using version 0.1 July 2016, so it could be a fixed issue in the new IDE.
