### ISSUE TITLE
IDE: add "navigator" (back/next) buttons 

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#25]

**Comment by LBDonovan** [comment]
@giuliomoro I think the browser back & forward buttons should do what you're after here, unless you mean something else?

**Comment by giuliomoro** [comment]
I am not sure what I mean, I am reporting a feature request from today's workshop. I think the idea is, ultimately, to be able to use the browser's navigation buttons to go to "the page that was previously viewed". I am not necessarily backing the feature, but a request it is and therefore I put it up here.

**Comment by LBDonovan** [comment]
They already do that ;)
