### ISSUE TITLE
IDE: console does no longer auto-scroll in Chrome

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#275]
Works fine in Safari/Firefox

**Comment by roberthjack** [comment]
I've seen this before and think it's to do with the zoom of the Chrome window. If you're above 100% then the auto-scroll of the console stops. If you zoom back to 100% it should start moving.

**Comment by LBDonovan** [comment]
Robbie is likely right - try pressing cmd+0 to zoom to 100%. I tried to fix this before but Chrome is buggy when zoomed - it also screws the look and layout of the settings checkboxes among other things.

**Comment by giuliomoro** [comment]
right, thanks: closed
