### ISSUE TITLE
IDE: 'About Bela' should be more informative

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#280]
Current example output:

```
About Bela

You are using Bela Version 0.2, October 2016. Bela is an open source project, and is a product of the Augmented Instruments Laboratory at Queen Mary University of London, and Augmented Instruments Ltd. For more information, visit http://bela.io
```

It would be useful if this contained e.g. Git version / branch. Or this could just be displayed at the bottom of the Project Settings window.

**Comment by giuliomoro** [comment]
Actually the "Version" number as reported here is pretty misleading, I'd suggest we remove it (e.g.: now `master` can run on both v0.2 and v0.3 images). Having the `git` commit hash or branch is not easy to do either (that is: baking it into the source code is out of question and if the board is updated through the `update_board` script, then the git hash would not be updated).

**Comment by jarmitage** [comment]
Ok. The problem that remains, that I have had in the past, is that it's impossible to tell whether an update has actually worked or not without testing random features.

**Comment by apmcpherson** [comment]
A better solution, if possible, would be to display two version numbers: the Bela image version, and the repo version. Perhaps a simplified numbering for the latter, e.g. an incrementing number for each commit, possibly a unique letter for each branch?

**Comment by giuliomoro** [comment]
The recommended procedure is for someone to download the zip archive and use the "update" button. Downloading the zip archive means that no git info are retained, therefore there is no way to get commit hash / branch.

**Comment by jarmitage** [comment]
Maybe the main repo can have a `.json` file somewhere with git / version info?

**Comment by giuliomoro** [comment]
This should be able to read image revision from `/etc/motd`

```
grep "Bela image" /etc/motd |grep -o "v[0-9]\{1,\}\.[0-9]\{1,\}\..*," | sed "s/,//"
```

**Comment by giuliomoro** [comment]
Having a json file somewhere means updating it.

The two options I see to have the version up to date:
- a "build" server that downloads from github and adds in the version file.
- built-in direct update from github!
