### ISSUE TITLE
Scope: undefined behaviour is leveraged

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#296]
With a modern compiler (e.g.: clang 4.0) you get:
```
In file Scope.cpp: [warning] passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs] column: 21, line: 213
```
See [here](https://www.securecoding.cert.org/confluence/display/cplusplus/EXP58-CPP.+Pass+an+object+of+the+correct+type+to+va_start).

It still seems to work, but it leverages undefined behaviour.

All in all, in my opinion the interface with `Scope::log(float value, ...)` should be abandoned.

**Comment by giuliomoro** [comment]
I vote to replace 
```
Scope::log(float value, ...)
```
with
```
Scope::log(const std::list<std::float> & myArguments)
```
which would be invoked with
```
scope.log({1.4, 4.2, 1.2});
```
(note the `{...}`).

An alternative is to use recursive variadic functions, but as far as I can tell, you cannot enforce type conversion, https://stackoverflow.com/questions/1657883/variable-number-of-arguments-in-c/16338804#16338804

**Comment by apmcpherson** [comment]
Will this force using C++11 for all Bela code? Do we already have that requirement, and are there any downsides?

I might suggest adding this as the preferred option and deprecating, but not removing, the old version, in the interest of maintaining compatibility with existing user code.
