### ISSUE TITLE
Typing in the "make parameters" text box behaves wierdly

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#3]
If you type something like
123
and you then you move your cursor back to after the 1 and type "45", you obtain
14235
this is because after key stroke the cursors jumps at the end, so after the '4', the cursor jumps at the end and therefore the '5' is appended to the string

**Comment by giuliomoro** [comment]
Also, typing in the "make parameters" box during a build (e.g.: try to build the core code), behaves wierdly, undoing changes, jumping around et similia

**Comment by giuliomoro** [comment]
Closed @LBDonovan 32d4aef1dfcf45c43a9bc6cd1fdf3a4917d389b4

**Comment by giuliomoro** [comment]
Unfortunately this is still active, though less bad.

Try to write a long string in there then place the cursors somewhere in the middle and hold press backspace.

**Comment by LBDonovan** [comment]
@giuliomoro are you sure? I just tried this in chrome and it worked fine

**Comment by giuliomoro** [comment]
It was true at the moment when I raised the issue. Chrome 52 on Mac. Will test again asap

**Comment by LBDonovan** [comment]
I'm fairly sure this is fixed

**Comment by giuliomoro** [comment]
no.
you need to get the IDE while it is pretty busy doing something else. Not easy to reproduce. I assume what is happening is that it is reloading the settings from the `settings.json` file before if is done writing to the file.

**Comment by LBDonovan** [comment]
This should be fixed by 10acdcc
