### ISSUE TITLE
IDE: Auto re-build project when drag-drop a file

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#30]
Maybe make it optional?
This way if you drag and drop a `_main.pd` the running program will reload it.

**Comment by LBDonovan** [comment]
@giuliomoro why does this need to happen? The files should appear in the list automatically.

**Comment by giuliomoro** [comment]
@LBDonovan renamed it for better clarity (I was in a rush when I posted it)

**Comment by LBDonovan** [comment]
Oh I see, so if Bela is running when you upload a file, it will stop, rebuild and run again?

That sounds like a good idea

**Comment by giuliomoro** [comment]
yes.
Make sure it waits for all the files uploaded within the same drag-and-drop before starting the build (so that it does not trigger multiple builds when dragging multiple files )
