### ISSUE TITLE
Running `mode_switches_detector` instance does not die if the program is not stopped with the STOP button in the IDE

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#314]
For instance, if you stop it with `make stop` or pressing the cape button, or simply restarting the program from the IDE without pressing "stop", you will see new instances of `mode_switches_detector` being created. This is on `dev-kernel-4.4.y-xenomai-3-support`.

**Comment by LBDonovan** [comment]
everything changed
