### ISSUE TITLE
update_board does hangs on `stopping Bela` without --no-frills option

### ISSUE THREAD

**Issue by LBDonovan** [BelaPlatform/Bela#326]
This happened when updating from `xenomai-3-stable` to `dev-scope` (and at least once before too)

**Comment by giuliomoro** [comment]
I assume this is due to the IDE not dying, right?
https://github.com/BelaPlatform/bela-image-builder/issues/48

**Comment by LBDonovan** [comment]
ohhh, yeah probably

**Comment by LBDonovan** [comment]
yes you're totally right
