### ISSUE TITLE
Detect hardware we are running on at runtime

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#333]
```
/sys/devices/platform/ocp/44e0b000.i2c/i2c-0/0-0050/eeprom
```

e.g. on PocketBeagle: A335PBGL00A21736GPB40212
e.g. on BeagleBone Black A335BNLT00C05116BBBK070D

**Comment by adanlbenito** [comment]
- Read eeprom on Bela program at startup to detect mini. 
- Check if coded is available for soft SPI on Ctag
- Check if pins are sorted for Salt

**Comment by giuliomoro** [comment]
There will be some C++ code living in `core/` that is compiled and called by the Bela program. The same code, alongside a wrapping `main()`, should be compiled as a stand-alone binary for the IDE to call (#377).

**Comment by giuliomoro** [comment]
done for now 9a33cc5f23d4c7c26457b8f39898be0053b94e3f, leaving open for CTAG

**Comment by giuliomoro** [comment]
the new way it should work:

* detect actual hardware
* apply user overrides (e.g.: use a subset of the available hardware)

in details:

## Detect actual hardware

* `bela_detectHw()`: read from `/run/bela` a variable `HARDWARE=`, if it doesn't exist:
  * Scan for all possible hardware (Bela cape, CtagBeast)
  * Cache the result to `/run/bela` (this is `tmpfs`)

## Apply user override (in `RTAudio.cpp`)

* `Bela_initAudio()`:  check for command-line option (e.g.: `--board=CtagFace`). If not provided:
  * `Bela_detectUserHw()` (in `board_detect.cpp`): checks for `BOARD=` in `/root/.bela/belaconfig`
* `Bela_initAudio()`: if one of the above is given, then evaluate if it is compatible with `HARDWARE`, and disable unused codecs (e.g.: the other CTAG board, or the Bela cape), or fail if incompatible.
