### ISSUE TITLE
Warnings on the IDE console.

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#335]
Getting
```
dircolors:
no SHELL environment variable, and no shell type option given
```
when setting project at boot

**Comment by giuliomoro** [comment]
This is weird. That `dircolors` is in `~/.bashrc`, which should only run by `bash` when you log into the BBB. @LBDonovan is there any difference in the way you run `make startuploop` vs the other invocations of`make` ? Or perhaps you run some other `bash` commands before or after that when setting a project at startup?

**Comment by LBDonovan** [comment]
I call it like this: `spawn('make', args, {cwd: belaPath})`

I guess it's possible using `cwd` like that rather than passing `-C` to the Makefile is the problem?
