### ISSUE TITLE
bela-cape-btn.c should not use edge interrupts

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#345]
... as these seem to be broken in the current 4.4.87-r121 Xenomai kernel and cause the kernel to OOOOPS

https://github.com/RobertCNelson/ti-linux-kernel-dev/issues/16

**Comment by dr-offig** [comment]
Hi Giulio, i'm noticing a constant stream of these unexpected IRQ traps, should I just ignore them? Would it help if I grounded pin P9_27?

**Comment by giuliomoro** [comment]
Hi Toby, are these triggered by pressing the button on the Bela cape? This was closed a long time ago, by reverting to polling instead of interrupt triggerinf, so if you get an up to date version of bela-cape-btn.c (from resources/tools/bela-cape-btn), it should work fine and not generate errors.

**Comment by dr-offig** [comment]
No button pressing required, just a constant stream from startup. This is using the BeagleBlone Black Wireless. The IRQ traps are both from 'edge' and from 'wl_core'.  It seems to work fine, but I guess must chew up some CPU logging these messages.  I'm using the latest stable image from the Bela wiki.

**Comment by giuliomoro** [comment]
Oh wait is this on the BBBW? I seem to remember seeing those, and they are not caused by our bela-cape-btn program. Just to make sure it's not our fault, run `systemctl disable bela_button` and reboot. Do you still see them?

**Comment by giuliomoro** [comment]
Yeah they show up on the BBBW, must be something wrong with some driver. Not a big deal, I think.
(PS: remember if you need the above to run `systemctl enable bela_button` if you want to re enable the bela button).
