### ISSUE TITLE
IDE stop and run button become unresponsive

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#346]
Observed on the basic/sinetone example. Run the example. Change block size to 2, recompile. Then change the block size to 128 (or any number higher than 2) – the IDE buttons becomes unresponsive – you cannot restart or stop the project. After about 30 seconds the project will stop. 

Tapping the button on the cape stops the project.

Observed in both Chrome and Firefox.

**Comment by giuliomoro** [comment]
I guess the change you were making in the menu was causing the issue as it was asking the IDE to do something (write to disk, could have been anything) and board was loaded with the running Bela process. Now I made the 2-samples setting to automatically enable high-performance mode (effectively removing the `sleep()` from the audio loop, this should give enough CPU juice to the IDE to stay alive as we get a 100us latency loopback!
