### ISSUE TITLE
Unable to open other projects after opening midi-poly-synth

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#347]
I try to open any other example project and get the following error

`Opening example 08-PureData/karplusStrong... Error: EROFS: read-only file system, unlink '/root/Bela/projects/exampleTempProject/voice.pd'`

**Comment by roberthjack** [comment]
The graceful shutdown via the button is also disabled, however after unplugging I can load other examples.

**Comment by giuliomoro** [comment]
probably a spurious bug. Unable to reproduce.
