### ISSUE TITLE
Rename Bela Generic MIDI USB Device 

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#350]
Currently shows up as  `Generic - USB MIDI Device`
Change to `Bela - USB MIDI Device` or similar

**Comment by LBDonovan** [comment]
I looked into this briefly but it doesn't seem to be possible, the name is set in the host computer's driver, not on the board afaict.

**Comment by jarmitage** [comment]
@LBDonovan if on a Mac, did you delete the MIDI device in Audio MIDI Setup before testing? This is a known thing where it will ignore the new name if it already knows the device

**Comment by giuliomoro** [comment]
tried that, it does not make a difference. However, this also means that you can conveniently set the name of the interface on first usage and have it show up with the same name in the future.
