### ISSUE TITLE
IDE: fileChangedPopup does not remember decision

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#360]
The [`workshop_watcher`](https://github.com/BelaPlatform/Bela/blob/dev-workshop/scripts/workshop_watcher) script sometimes fails to automatically update and build projects, because the IDE asks the user if they want to overwrite the file changes.

Unlike the Overwrite popup when the user drags and drops a file onto the IDE, the `fileChangedPopup` does not offer an option to _Do not ask again this session_, and does not consider the `askForOverWrite` flag if that has already been set elsewhere by the user.

<img width="471" alt="2017-11-16 at 11 28 46" src="https://user-images.githubusercontent.com/2885827/32902786-58baa838-cac1-11e7-934c-61e38c8c6a86.png">

https://github.com/BelaPlatform/Bela/blob/9584252deab5a9317368eff5419f6dcfec7d54bf/dev/src/IDE-browser.js#L317

<img width="469" alt="2017-11-16 at 11 31 42" src="https://user-images.githubusercontent.com/2885827/32902942-c10be5d2-cac1-11e7-8946-3234e7a94cac.png">

https://github.com/BelaPlatform/Bela/blob/76d9c1eec756fc8a33280f79489536d4c06b97de/dev/src/Views/FileView.js#L8

**Comment by jarmitage** [comment]
Not really sure what's going on with this in the workshop branch:

https://github.com/BelaPlatform/Bela/commit/d802a903c9aa64842e2454f4f26b595985ccd1b0

**Comment by jarmitage** [comment]
This may just have been due to #361

**Comment by giuliomoro** [comment]
This is not the case anymore. In fact, the popup has (inadvertently) been removed altogether.
