### ISSUE TITLE
IDE: Upload an update patch not working

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#361]
I can see an update in `/tmp/belaUpdate` but the IDE itself hasn't been updated

Where is the actual IDE stored?

**Comment by jarmitage** [comment]
Second attempt seemed to work after making some arbitrary code changes to `IDE-browser.js`

**Comment by giuliomoro** [comment]
so was there a bug? What changes did you make?

**Comment by jarmitage** [comment]
A few times now I've used the `Upload an update patch` option but the updates have not taken place. 

I was editing `IDE-browser.js` to see if I could hack https://github.com/BelaPlatform/Bela/issues/360
