### ISSUE TITLE
Make Parameters field in IDE is hard to use due to font and size

### ISSUE THREAD

**Issue by cpmpercussion** [BelaPlatform/Bela#362]
The make parameters field in the IDE is difficult to use because:
- It's too small to see a reasonable number of parameters
- The font makes it hard to see the difference between "l" and "I". (Just like here.)

It would be great to something like a multiline box with a fixed width font. :-)

**Comment by cpmpercussion** [comment]
duplicate of #251

**Comment by giuliomoro** [comment]
Let me add that we should also fix the weird "semicolon-separated" syntax.

**Comment by giuliomoro** [comment]
Reopening because the size of the field has not actually been fixed.

**Comment by giuliomoro** [comment]
@TheTechnobear OMG
e988721da40fe405d44fe0f03daee1772c7f9a6b

<img width="431" alt="Screenshot 2021-01-28 at 18 08 12" src="https://user-images.githubusercontent.com/4260604/106180433-2c3a3b80-6194-11eb-9599-95cce107abd4.png">

**Comment by TheTechnobear** [comment]
ooh nice...  i can finally see all my make parameters :)
