### ISSUE TITLE
If pd patch contains empty comment then patch doesn't render in IDE

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#37]
Raised on the forum here: http://forum.bela.io/d/40-how-to-address-the-i-o-via-pd/11

**Comment by LBDonovan** [comment]
This is a bug in [pdfileutils](https://github.com/sebpiq/pd-fileutils)

**Comment by giuliomoro** [comment]
Still, it is our problem.

**Comment by LBDonovan** [comment]
Nice. You should do a pull request on the pdfileutils repo for this!

**Comment by giuliomoro** [comment]
I forked their repo, but this file cannot be found there with this name.
Did you simply copy and rename [this](https://github.com/giuliomoro/pd-fileutils/blob/master/dist/pd-fileutils-latest.js) or did you "build it" yourself?

**Comment by LBDonovan** [comment]
I copied and renamed that file.
