### ISSUE TITLE
sclang symbol lookup error on the better-i2c branch

### ISSUE THREAD

**Issue by Nathnainiel** [BelaPlatform/Bela#374]
I need I2C for a project so I upgraded to the better-i2c branch. Unfortunately, when I run any SuperCollider example after that I get this error:

```Building lib/libbela.so
sclang: symbol lookup error: /root/Bela/lib/libbela.so: undefined symbol: _ZTI3I2c
Makefile:511: recipe for target 'runide' failed
make: *** [runide] Error 127
Bela stopped```

Manualy copying the libbela.so file from the master branch installation solves the issue until the next upgrade.

**Comment by giuliomoro** [comment]
Yeah makes sense. See if https://github.com/BelaPlatform/Bela/commit/e7d3a079accf7d452079968670e8fe6d03b43e78 fixes it: update your board to the `better-i2c` branch again and re-build `libbela` (either run `make lib` or run a Supercollider project from within the IDE.

**Comment by Nathnainiel** [comment]
Yep, now it works!
