### ISSUE TITLE
Scope: web socket uses hard coded local IP address 

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#375]
https://github.com/BelaPlatform/Bela/blob/8d0196cb5748ad46a13b973c836bd479a5bd49d4/dev/scope-src/scope-browser.js#L30

https://github.com/BelaPlatform/Bela/blob/6e54417d9b08b49f5d68d9f60a6989f1d3020acd/IDE/public/scope/js/scope-worker.js#L4

**Comment by jarmitage** [comment]
Tried this but unable to get a connection

```javascript
var ip = location.host;
var ws = new WebSocket("ws://"+ip+":5432/scope_data");
var ws_onerror = function(e){
	setTimeout(() => {
		ws = new WebSocket("ws://"+ip+":5432/scope_data");
		ws.onerror = ws_onerror;
		ws.onopen = ws_onopen;
		ws.onmessage = ws_onmessage;
	}, 500);
};
ws.onerror = ws_onerror;
```

**Comment by giuliomoro** [comment]
did you `gulp` ? 

`console.log("ws://"+ip+":5432/scope_data")` ?

also, what does the console say?

**Comment by jarmitage** [comment]
If browser is at `http://192.168.7.2/scope/`:
```javascript
scope-worker.js:8 WebSocket connection to 'ws://192.168.7.2:5432/scope_data' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
scope-browser.js:32 WebSocket connection to 'ws://192.168.7.2:5432/scope_control' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
If browser is at `http://192.168.1.XXX/scope/` (with Bela on WiFi):
```javascript
scope-worker.js:8 WebSocket connection to 'ws://192.168.1.XXX:5432/scope_data' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
scope-browser.js:32 WebSocket connection to 'ws://192.168.1.XXX:5432/scope_control' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by jarmitage** [comment]
`console.log("ws://"+ip+":5432/scope_data")` => `ws://192.168.7.2:5432/scope_data`

**Comment by giuliomoro** [comment]
I think you may have forgotten to `gulp`? If you can't be bothered to set up your `gulp` environment, for quick fixes like this you can edit the `gulp`-generated files in `IDE/public/scope/js/` directly.

Anyhow, fixed now.

**Comment by jarmitage** [comment]
Hmm that's weird, I had gulp running as in the instructions here: https://github.com/BelaPlatform/Bela/wiki/Developing-for-the-IDE

I will reboot and try again with your fix

**Comment by giuliomoro** [comment]
did you also edit `Bela/IDE/public/scope/js/scope-worker.js` ? 
you could just `grep  -RI 192.168.7.2 IDE` to make sure there is nothing left in there. Also maybe your browser is lazy in reloading the js files?
