### ISSUE TITLE
IDE not loading after uploading PD file

### ISSUE THREAD

**Issue by Genzo3** [BelaPlatform/Bela#381]
Hi!

I've been using the Bela for two weeks without problems. Today, I uploaded a PD file and some somples. The CPU usage was at 85%, but, I unpluged the Bela from my computer and tested it. No sound, and when I try to connect the Bela again the server 192.168.7.2 doesn't respond and I'm not able to see the IDE.

Any ideas on how to get to the origin? Is there any way to do a memory erase or something?

Thanks!

**Comment by giuliomoro** [comment]
what do you mean you "unplugged the Bela from my computer and tested it" ?

**Comment by Genzo3** [comment]
I uploaded the files to the Bela using the IDE and unpluged the Bela and used an external battery (5v) to test the hardware without the computer ...

**Comment by Genzo3** [comment]
I've been doing this with other PD files without problem but today something went wrong ...

**Comment by giuliomoro** [comment]
Did you set the project to run on boot? What image are you running? Was the project running ok in the IDE?

**Comment by Genzo3** [comment]
SOLVED! It took about 30 minutes to connect. I managed to delete the PD file, rebooted and averything was ok! I guess that the file was too heavy for the Bela, and also contained some errors. 

We are back!

PS: By the way, How can I convert the analog ins from several pots into a numeric value instead of signal (~)? I'm already controlling line levels without problems, but I'm having issues translating them into data ...

**Comment by giuliomoro** [comment]
If the program is very CPU-intensive, then it may take a looong time for the operating system to load and the board to become available again over the network. However, I would expect the sound to work just fine during this time (unless it relies on reading files/using network or other Linux stuff). You can stop the program at any time by pressing the button on the Bela cape, to take back control of the board.
