### ISSUE TITLE
Wiki: Document default search path for PureData externals

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#384]
To add to potentially this page: [Running Puredata patches on Bela](https://github.com/BelaPlatform/Bela/wiki/Running-Puredata-patches-on-Bela)

TL;DR to use PureData externals across projects: create the folder `/root/Bela/projects/pd-externals` and put them in there.

@giuliomoro:
> The default search path is the one you find in https://github.com/BelaPlatform/Bela/blob/master/core/default_libpd_render.cpp#L384-L385  : `"."` (current folder) and `"../pd-externals/"`, that is the folder `/root/Bela/projects/pd-externals`. This means that if you put something in either of those folders, your program will be able to open it. I don't think the `-lib` startup option for Pd has an equivalent in libpd (and therefore Bela). The way I normally do it  is to create an object with the name of the library (e.g.: `[ml]`), which should then allow you to create other objects from that library. In order for this approach to work, you need the `[ml]` object to be created BEFORE the objects from the library. The order of creation is the order in which you create the objects in the Pd patch. So you can basically create your `[ml]` as the first object of the patch (or subpatch), or - if you already have a working patch, select it all, cut, create the `[ml]` object, paste.
> The `pd-externals` folder does not exist by default because it would just make things confusing, if it shows up as a project folder that does not contain a project

I'm not sure if this is the best design solution for using Pd externals with Bela, but at least this process should be documented for now.

**Comment by jarmitage** [comment]
@giuliomoro will this work recursively?

**Comment by giuliomoro** [comment]
the same way it works for Pd: if you an external is in a subfolder you need to create an object `[subfolder/exernal ]`.
If you want to add folders to the path, you can edit `core/default_libpd_render.cpp` and add them there.

**Comment by roberthjack** [comment]
Updated on the [wiki](https://github.com/BelaPlatform/Bela/wiki/Running-Puredata-patches-on-Bela#using-an-externals-folder)
