### ISSUE TITLE
Allowing for arbitrarily large blocksizes

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#388]
New idea: keep whatever the current hardware block size is, but add FIFOs to a separate thread to run the audio in. Basically, `render()` would now be called from within an `AuxiliaryTask`, in a way that is totally transparent to the user. If Bela is using RTDM (as it does on v0.3.x images), this should also come pretty cheap (I estimate the penalty is one context switch (~17us) every time the hardware buffer is full, that is about 0.5% CPU time with a blocksize of 128) and still run at xenomai-guaranteed priority.

The other solution is to use DDR instead of PRU RAM, but that is much more complicated.

**Comment by apmcpherson** [comment]
This seems reasonable from a performance standpoint, and certainly easier than the PRU-DDR approach. You could make the internal `PRU.cpp` run at a higher priority than 95, so the priority of `render()` doesn't have to be changed. For small block sizes I would keep things as they are.

My only objection is philosophical, in that I think good code should be written to not need big block sizes, but I realise that this is often practically impossible when using legacy code bases or even when in a hurry to mock something up.

**Comment by giuliomoro** [comment]
Blocksizes achievable via hardware buffers will run in the standard mode, larger blocksizes will have to run FIFOed. Xenomai's RT message queue could be useful here (see an example implementation [here][https://github.com/BelaPlatform/Bela/blob/master/core/AuxTaskRT.cpp))

**Comment by giuliomoro** [comment]
almost-non-pseudocode:
```
// ioToComputation and computationToIo are a file descriptor for a message queue

// in the IO thread
size_t sizeOfComputationToIo = //number of bytes that need to be sent from Computation to Io
size_t sizeOfIoToComputation = //number of bytes that need to be sent from Io to Computation

while(!gShouldStop)
{
__wrap_read(...); // wait for the PRU to signal a buffer is available
// copy from PRU memory to hardwareInBuffer
__wrap_mq_send(ioToComputation, hardwareInBuffer, sizeOfIoToComputation, 0) 
__wrap_mq_receive(computationToIo, hardwareOutBuffer, sizeOfComputationToIo, &prio);
// copy from hardwareOutBuffer to PRU memory
}

// in the Computation thread
int computationBuffersPerAudioBuffer = computationBlockSize/hardwareBlockSize; // needs to be an integer ratio!
char fromIoBuffer[sizeOfComputationToIo * computationBuffersPerAudioBuffer];
char toIoBuffer[sizeOfIoToComputation * computationBuffersPerAudioBuffer];
while(!gShouldStop)
{
  for(int n = 0; n < computationBuffersPerAudioBuffer; ++n)
  {
    __wrap_mq_receive(ioToComputation, &(fromIoBuffer[n*sizeOfComputationToIo]) , sizeOfIoToComputation, &prio);
  }                         
// convert ints to floats (stuff that is in PRU::loop())
  render();
// convert floats to ints (stuff that is in PRU::loop())
  for(int n = 0; n < computationBuffersPerAudioBuffer; ++n)
  {
    __wrap_mq_send(computationToIo,  &(toIoBuffer[n*sizeOfComputationToIo]), sizeOfComputationToIo, 0)) 
  }
}
```

**Comment by giuliomoro** [comment]
Done, latency is about `(converterGroupDelay+ioBlockSize*2 + userBlocksize)/audioSampleRate`.
Where
`converterGroupDelay = 39` on Bela (something else on CTAG)
`ioBlockSize = 128` on Bela
`ioBlockSize = 64` on CtagFace
`ioBlockSize = 32` on CtagBeast
(higher values may be possible by considering the PRU memory available and whether audio inputs and/or analog I/O are used).

`userBlockSize` is the one specified by the user with `-p` (and/or through the IDE).

CPU usage has a baseline of about 6%  due to running the "audio thread" (now, I/O thread, at `BELA_AUDIO_PRIORITY+1`) at 128 samples per block and the "fifo audio thread" (i.e.: the one that runs `render()`, at `BELA_AUDIO_PRIORITY`).
