### ISSUE TITLE
IDE: `example docs` button opens empty page when no Doxygen exists

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#389]
<img width="1175" alt="2018-03-27 at 10 36 57" src="https://user-images.githubusercontent.com/2885827/37963784-4500183e-31b7-11e8-923a-9a35be64760b.png">

**Comment by giuliomoro** [comment]
this button is now gone, so this is no longer an issue.

**Comment by giuliomoro** [comment]
The button has been removed, issue is no longer valid.
