### ISSUE TITLE
gShouldStop should be reset to `false` in Bela_initAudio() or Bela_startAudio() ...

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#40]
... while right now it is only set to `false` once at startup. 

A user found a problem with the current state of things when trying to restart the audio engine.
http://forum.bela.io/d/48-stopping-and-starting/3

@apmcpherson Can you see any reason why it would a bad idea to set `gShouldStop = false` in `Bela_startAudio()` ?

**Comment by apmcpherson** [comment]
That sounds like the right approach. Set it to false at the beginning of Bela_startAudio(), before creating any of the RT threads.
