### ISSUE TITLE
Missing samples, documentation, projects directory; possibly incomplete IDE

### ISSUE THREAD

**Issue by notshi** [BelaPlatform/Bela#41]
Have been using the IDE to play around with the example projects but things seem incomplete.

1. Clicking on 'example docs' lead me to pages with Cannot GET /documentation/xxx.html messages.
2. Downloading the entire projects directory gets me a rather bare folder of two more rather bare folders, 'basic' and 'exampleTempProject'.
3. The sample-piezo-trigger tells me there is a sample.wav file somewhere but I can't seem to find it in Belaboot.

Should I be cloning the repo to use Bela?

On the plus side, I was successful in making it go beep via the sinetone example so that was cool.

**Comment by giuliomoro** [comment]
1) on what project did you click "example docs"/what was the full URL?  all the ones that I have tried work fine . @LBDonovan may have a better idea of what is going on here

2) "download all" is supposed to do exactly what you describe: download the entire project folder. This folder starts containing only a folder called "basic". Every time you build one of the example projects, it goes into the folder "exampleTempProject", unless you save it as a new project (in which case it goes to its own folder) or you create a new project. So I would say that if you never created a new project or "saved as" an existing example, then everything is normal.

3) The sample-piezo-trigger example was fixed a couple of days ago (more improvements on sample-based examples coming soon)

- Cloning the repo is an option, but downloading from the master branch is just as fine. Make sure you use one of the workflows described in the [wiki](https://github.com/BelaPlatform/Bela/wiki/Updating%20Bela) to update the code on the board

**Comment by notshi** [comment]
1. http://192.168.7.2/documentation/sample-piezo-trigger_2render_8cpp-example.html
2. Sorry, I guess I misunderstood what it was supposed to do!
3. Ooh, thank you! Will do just that.

**Comment by LBDonovan** [comment]
Hi @notshi, thanks for pointing out those broken links. I just pushed a commit which fixes them, so if you update your board with the instructions @giuliomoro gave, they should be working now.

**Comment by disastrid** [comment]
Hi @notshi, thanks for bringing these issues to our attention. I'm adding this information to this thread in case it's useful to you and others.

- The "Download all projects" button does what Giulio describes, which is download all *your* projects (which will indeed be quite bare if you haven't created any). After reading your post I think you might be looking to download the example projects to have a look at them locally. These can be found here: https://github.com/BelaPlatform/Bela/tree/master/examples

**Comment by notshi** [comment]
Ooh, thanks very much @LBDonovan @disastrid those will be mighty helpful indeed!
