### ISSUE TITLE
Some backwards on new Bela board

### ISSUE THREAD

**Issue by sunwell1994** [BelaPlatform/Bela#414]
On the old bela board, it is possibile to use osc send out packages and write in files at the same time. However, in the new version, it returns underrun and crossed pointer error.

Another backward is that the response of stop command is of high latency. What is the kernal difference of the two versions?

**Comment by giuliomoro** [comment]
Sorry I didn't see this earlier.  There should be no noticeable performance difference for OSC and WriteFile classes between the two images. Could you provide some example code that outlines the issue and mention what versions you are running it on?

**Comment by sunwell1994** [comment]
The original version is V 0.0 and the current version is V0.3.
The main task is to use bela board play acoustic signal and receive the reflection signal. Then we try to write to file and send data package at the same time and real time. In the old version, everything is fine.
However in the new version, the write pointer will cross. If I just try OSC real time without writing into a new  file, there will be 3 blocks underrun at the beginning.
In my opinion, the new bela board cannot hold as much workload as before. By the way, is there any change on the hardware side of the new bela board? Thanks

**Comment by giuliomoro** [comment]
no change on the hardware. Version v0.0 does not exist, there are v0.1.0, v0.1.0a , v0.2.0, v0.2.0a, v0.2.1. Do you know what version of the Bela code you are running on the older image? When did you last update it? Could you send a minimal code example that reproduces your issue on a v0.3.x image?

**Comment by sunwell1994** [comment]
I find that there are two pages for release. The first one may be what you refer to: [https://github.com/BelaPlatform/bela-image/releases](bela-image). However, I check the page [https://github.com/BelaPlatform/bela-image-builder/releases/](bela-image-builder). Here you can find V0.0 and V0.3.2.

**Comment by giuliomoro** [comment]
https://github.com/BelaPlatform/bela-image/releases is the old page, where revisions up to v0.2.1 were released.
https://github.com/BelaPlatform/bela-image-builder/releases/ is the current page, which should be used moving forward. It is true, v0.0 is there, however it does not have an image binary that can be used, therefore you cannot have v0.0 on your board.

Could you send a minimal code example that reproduces your issue on a v0.3.x image and which was working fine on a pre- v0.3.x image?

**Comment by sunwell1994** [comment]
the size of blob packages is not too big. It is about 441 * 4  * 4 = 7056 bytes for a period of 10ms, which is about  0.67Mb/s. The bandwitdth is large enough to transmit the data

**Comment by giuliomoro** [comment]
you mentioned you are writing to a file at the same time? Or are you just sending OSC messages?

**Comment by sunwell1994** [comment]
Even if I just send OSC messages, there will be 3 blocks to underrun and be dropped at first. Besides, there will be some processing on reading the audio file in the setup().

**Comment by giuliomoro** [comment]
Ok. Can you confirm what version of the Bela code you are running? The image version (as returned by `cat /etc/motd`) and if you have updated the Bela core code since you updated the image.

**Comment by sunwell1994** [comment]
Ok. I will check it in the lab tomorrow.Thanks.

**Comment by sunwell1994** [comment]
Hi, I am sorry that we made a mistake in the version before. In fact,
old version: Bela release image, v0.2.0b, 15 December 2016
new version: Bela release image, v0.3.0, 16 October 2017

**Comment by giuliomoro** [comment]
Ok, did you update the code on the board after you updated the image?

**Comment by sunwell1994** [comment]
We transfer the original code to new image

**Comment by giuliomoro** [comment]
@sunwell1994 do you need any further assistance on this?
