### ISSUE TITLE
Legibility issues in IDE

### ISSUE THREAD

**Issue by notshi** [BelaPlatform/Bela#42]
Apologies if this is the wrong place to bring this up.

The current text on the IDE is rather hard to read - I saw that you have themes for it but unsure where options are to change to a darker layout or if it possible to apply my own theme.

Tried mapping the CSS locally but your cache break query parameter makes this impossible in the Chrome debugger.

**Comment by LBDonovan** [comment]
Hi @notshi, adding a choice of styles for the IDE is definitely on our list of things to do, but it hasn't been implemented yet.

The editor is powered by [ace.js](https://ace.c9.io/#nav=about) which uses 'themes' to control the CSS styling. There are a couple of options for changing the themes manually:

1. Download one of the preconfigured ace themes [from their github repo](https://github.com/ajaxorg/ace-builds/tree/e94cb3c7ffccfb2e565cc857f07a988c0989e527/src) (the files are of the format 'theme-<name>.js', the IDE currently uses the chrome theme) and upload it to ~/Bela/IDE/public/js/ace/ on your BeagleBone. Search through the file ~/Bela/IDE/public/js/bundle.js for the line 'this.editor.setTheme("ace/theme/chrome");' and change 'chrome' to the name of your new theme.

2. Manually edit the CSS inside the file ~/Bela/IDE/public/js/ace/theme-chrome.js

Note that this will only affect the styling of the actual text editor, and not the console or tabs etc.

**Comment by notshi** [comment]
Fantastic, thank you @LBDonovan for the notes!

**Comment by apmcpherson** [comment]
This came up again at the STEIM workshop today. In this case, the white-on-grey text in the documentation was hard to read for some users. A high-contrast option would be useful for accessibility.

**Comment by TheTechnobear** [comment]
+1 
also from a UI perspective, the current buttons, look like they are 'greyed out' i.e. disabled/inactive

**Comment by giuliomoro** [comment]
things have gotten much better with the new IDE. Docs is no longer gray on white. Closing this, feel free to reopen if you have  something more specific.
