### ISSUE TITLE
IDE: upon refresh, no project is loaded

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#435]
dev-ide branch, tested on Chrome

* Select a project (e.g.: `basic`), so that it displays `render.cpp`
`Bela/IDE/settings.json` will be like:
```
cat settings.json
{
  "project": "basic",
  "liveAutocompletion": 1,
  "liveSyntaxChecking": 0,
  "verboseErrors": 0,
  "cpuMonitoring": 1,
  "cpuMonitoringVerbose": 0,
  "consoleDelete": 0,
  "viewHiddenFiles": 0
}
```

* Refresh the page (cmd+R), you will get no file displayed. The dropdown will show "Choose a project from your board" but then the list is empty.
IDE log:
```
May 30 11:19:14 bela node[1528]: setting pwd timeout
May 30 11:19:14 bela node[1528]: no project set to run on boot
May 30 11:19:19 bela node[1528]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
```
inspector log:
```
bundle.js:623 Uncaught TypeError: Cannot read property 'project' of undefined
    at Socket.<anonymous> (bundle.js:623)
    at Socket.Emitter.emit (socket.io.js:5657)
    at Socket.onevent (socket.io.js:5183)
    at Socket.onpacket (socket.io.js:5141)
    at Manager.<anonymous> (socket.io.js:5522)
    at Manager.Emitter.emit (socket.io.js:5657)
    at Manager.ondecoded (socket.io.js:4668)
    at Decoder.<anonymous> (socket.io.js:5522)
    at Decoder.Emitter.emit (socket.io.js:2556)
    at Decoder.add (socket.io.js:6156)
```

* Try cmd+shift+R ("hard" refresh) and you will still get no project  file loaded, and  the same logs as above. However, now the dropdown says "--Projects--" and it displays the projects in the `projects/` folder

**Comment by LBDonovan** [comment]
Is this on the // URL? Because that is not the correct URL, and the IDE is not expected to work on the incorrect URL.
