### ISSUE TITLE
IDE: adding check for mode switches

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#45]

**Comment by giuliomoro** [comment]
Added working example of a small C utility that can display the number of mode switches. @LBDonovan see if you want to call this directly or do something else with it.

**Comment by giuliomoro** [comment]
A better option could be for the task to report them itself using an `rt_task_hook` which is triggered every time a mode switch takes place.

http://www.xenomai.org/documentation/trunk/html/api/group__task.html#ga7452f367f9e17bf2fc0b70f717b96dd8

**Comment by giuliomoro** [comment]
@TheTechnobear required elsewhere a running count, can we add this so to have CPU: / IDE: / MSW: ?

**Comment by TheTechnobear** [comment]
sorry, been meaning to check out, what the IDE 'Xenomai stats' gave me...  
it does look like exactly what i need - the only 'negative' is its producing so much output, so on the toolbar would be useful OR the ability to turn it on/off a little easier (checkbox on the toolbar?) 
but honestly, now I know the option is there, its not big problem for me to turn it on/off when I need to check for mode switches.
