### ISSUE TITLE
D-Box software

### ISSUE THREAD

**Issue by javajive64** [BelaPlatform/Bela#46]
Total newbie, Trying to get the D-box started but have a few issues
1. Page 37 of assembly guide, I downloaded the zip as described but when trying to update bela error "not a valid zip archive"
2. Page 39 couldn't upload sound files error "can't open binary files"
3. Ran the Run command anyway, made it halfway through then got the error "Could not open directory usersounds"

Ideas?

**Comment by apmcpherson** [comment]
Hi there, thanks for the feedback. You'll need to update Bela for the D-Box software to run properly. Here are instructions on how to do that: https://github.com/BelaPlatform/Bela/wiki/Updating-Bela

Just make sure that when you download the zip archive it doesn't get expanded automatically by your browser. 

"Can't open binary files" may just mean it can't display them, but if they show up in the directory they are still fine.

For help on getting up and running with the D-Box the forum is your best place to go: forum.bela.io. Github is for bug tracking mainly. Of course there may be bugs -- if you find them in the software, this is the place; suggestions for the manual can be opened as issues on the D-Box repo: https://github.com/BelaPlatform/D-box
