### ISSUE TITLE
Re-add support for Csound on BelaMini

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#462]
- test that Victor's binary is working fine
- replace the existing `.deb` in resources/stretch/deb/`
- revert (all or part of) the IDE changes from https://github.com/BelaPlatform/Bela/commit/b05b13c8b2b49d2d6997daa4388d3d9ab4e3cc67  and https://github.com/BelaPlatform/Bela/commit/d82d08cb315c36b9058ea22d753d14230a5c9805

**Comment by LBDonovan** [comment]
0e0824021758a61a06acb12cada4c7a230c680fc
ea5b169e0a1a5ec35421071ab42f0c0cfbfca540

**Comment by giuliomoro** [comment]
and https://github.com/BelaPlatform/Bela/commit/d54893ce6ee1531580c6389f2c92a1b22d4cdeb6
