### ISSUE TITLE
Security Boot Win10 x64

### ISSUE THREAD

**Issue by adrier** [BelaPlatform/Bela#464]
Hi,

I am the proud owner of a Bela Mini I've just received.
While tyrying to install the driver available on the wiki for Windows x64 I am experiencing a difficulty: the manufacturer of my laptop (Gigabyte...) does not allow for Desactivation of the Security Boot. Even as an admin. I wen to the BIOS and confirm that I do not have access to that option.
A solution would be to change the Security Boot Keys, but as much as I am excited to use the Bela Mini, I am not willing to take this risk.

Did anyone experience this issue already?
Would there be a solution not involving a VM or dual boot?

Thanks for your help.

Best,

Adrien

**Comment by LBDonovan** [comment]
H Adrien

I'm not particularly familiar with Windows driver issues, but if you can't get RNDIS installed, I would say you have a few options:

- Check if Bela appears as a network device (at 192.168.7.2 or bela.local) anyway. Some Windows versions have built-in RNDIS drivers already.
- Check if it appears as a serial device (usually called usbmodem__bela__ or similar). This requires the serial FTDI driver but again, you might have it already. With a serial connection you can't use the IDE or network features, but you can login directly to the system and edit/run/compile programs from the command line.
- Get a VM. Ubuntu on VirtualBox is free, relatively easy to set up, and has worked fine in my experience.

**Comment by giuliomoro** [comment]
I just looked into this and it turns out that your board should just work fine on Windows 10 as it is, with no need to install drivers (I checked with Windows 10 pro Version 1709, OS Build 16299.431). You should be able to go to 192.168.7.2 after ~30 seconds since you plugged in the board. Can you please check?

**Comment by giuliomoro** [comment]
If it does not work, please get back to us and I have another solution, which I cannot seem to be able to test on this Windows machine here because I got it working already and cannot "undo" it!

**Comment by adrier** [comment]
Hi,

Looks like it's working by simply accessing 192.168.7.2 ...
Thanks for your help.

Adrien
