### ISSUE TITLE
IDE doesn't show up Bela connected

### ISSUE THREAD

**Issue by jestern77** [BelaPlatform/Bela#473]
HI there maybe it's stupid. I see Bela connected but when I try to connect with IDE I get redirected to another page that tells me all is fine. But I can't get to the IDE. I have all installed. Actually BELA was working fine last week. Now this is strange.

![screen shot 2018-07-06 at 13 59 59](https://user-images.githubusercontent.com/6736085/42377791-233cf09c-8125-11e8-9c3e-fc1e0cb89d48.png)

**Comment by giuliomoro** [comment]
it seems that your SD card has popped out and that the BeagleBone is booting from the built-in storage, which still has the BeagleBoard.org image!

**Comment by giuliomoro** [comment]
si? no?

**Comment by jestern77** [comment]
Still trying (in the middle of other stuff) no success today also connectivity seemed super slow. Gonna try to flash it again tomorrow.

**Comment by giuliomoro** [comment]
If you are getting that IDE, it definitely means that it is not booting from the SD card, so either the SD card is corrupted, or there is something wrong with the SD card slot. Sometimes the tiny pins of the slot get bent if it is not treated with care, but you can often bend them back into place
