### ISSUE TITLE
Power light on but board won't boot

### ISSUE THREAD

**Issue by NLEW** [BelaPlatform/Bela#475]
Hi, I'm a bit new to this stuff but I'm supposed to be using a Bela in a performance tomorrow and it was all working fine the other day ... but when I turned the power on today, it didn't seem to boot up. It wont run any programs, show in the IDE, or as an external drive on my computer. The only sign of life is that the power button lights up. I'm hoping I've not somehow fried it. Any help would be really appreciated

**Comment by giuliomoro** [comment]
hmmm.
Is this Bela or BelaMini?

Are you using an SD card? Is it properly inserted? Is there any hardware connected to the board?

**Comment by giuliomoro** [comment]
that sounds very sad.

Can you try removing the cape and booting the board without it?

If that does not work, while the cape is off, try flashing an SD card and booting from the SD card? 
See here: https://github.com/BelaPlatform/bela-image-builder/releases/tag/v0.3.5a (you will need to hold press the USER button when you power it up).

It seems that the board may be dead; these are just desperate attempts.

**Comment by NLEW** [comment]
Aw no , well thank you, I'll try the stuff you said. Just wondering, if it still doesn't work, do you guys do replacements at all? Because I've only had it for 6 months and not used it heavily at all ... I cant think what I could have done to cause it to break.

**Comment by NLEW** [comment]
Great, thanks for your help!
