### ISSUE TITLE
D-box does not build due to missing ne10_fir_float_neon

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#477]
it seems like that was - for whatever reason - left out of the latest ne10 build

**Comment by adanlbenito** [comment]
can this be somehow related to this issue?
https://github.com/projectNe10/Ne10/blob/f303d431d6366466ae118877c00228fa8ab50212/modules/dsp/NE10_init_dsp.c#L50

**Comment by giuliomoro** [comment]
no I think it was just something bad in the build. I tried another one but didn't fix it, dammit. https://github.com/BelaPlatform/Bela/commit/a334d6754aa1d1d2d52f705ccc0913bd815a240a
