### ISSUE TITLE
IDE: how do I copy the console contents?

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#48]
Say I get a linker error: how do I copy it so I can paste it into google?
Select /copy does not work, because when selecting with click and drag, the line disappears as soon as you release the cursor

**Comment by LBDonovan** [comment]
It's still not possible to copy compiler errors

**Comment by giuliomoro** [comment]
I actually can, but it's a bit tricky: you need to click above it and then drag down and hit cmd C / ctrl C
