### ISSUE TITLE
Examples: Pd CustomRender does not work with Bela Mini

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#498]
Due to this line in render.cpp which checks for an eqaul number of analog ins and outs:
```
if(context->analogInChannels != context->analogOutChannels || context->audioInChannels != context->audioOutChannels){
		fprintf(stderr, "This project requires the number of inputs and the number of outputs to be the same\n");
		return false;
	}
```

**Comment by giuliomoro** [comment]
it should have been updated as of 942941f62caddbaa9fb2b72af76e2c16f19d4143 . However, many things have changed now, so it would be good to re-create the custom-render C++ file, by starting from `core/default_libpd_render.cpp` and re-add the "custom" sections from the stale examples/08-PureData/customRender/render.cpp`. The "custom" sections are clearly marked there, so it should be a 10 min job. Fancy trying @roberthjack?

**Comment by giuliomoro** [comment]
Closed https://github.com/BelaPlatform/Bela/commit/1362b8fde934df5db5b5b833978f251186077759
