### ISSUE TITLE
IDE: update Bela button does not display properly

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#50]
Firefox and Edge and Internet Explorer on Windows 10, see images below
![screenshot 1](https://cloud.githubusercontent.com/assets/4260604/17267174/f5605cec-55fa-11e6-95f7-fa36e2d8c0c2.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/4260604/17267175/f560ee5a-55fa-11e6-9440-fe48bab2f36b.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/4260604/17267328/e2ebc648-55fd-11e6-8cca-f813e2a194d3.png)

**Comment by LBDonovan** [comment]
This should be fixed but it needs testing
