### ISSUE TITLE
IDE: on Windows 10 "Update Bela" does not work

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#51]
NOT working in Chrome, Firefox, Edge, Internet Explorer on Windows 10.

Symptoms: when clicking "updateBela" and selecting a file, after clicking "update", the console immediately returns a message "not a valid zip archive".

- the javascript console displays
```
not a valid update zip archive
```
- nothing is displayed in the node console.log .
- no file is created in ~/Bela/updates/

NOTE: the regular drag-drop files in the browser window to add files to the project works just fine (even for large files).
Is there a way to make the "update bela" upload behave like one of the drag/drop uploads?

Raised here http://forum.bela.io/d/52-updating-bela

Not sure if this is related with this (don't think so)
https://productforums.google.com/forum/#!msg/chrome/H-BhgSbCx-E/MIkFe2V2CgAJ

**Comment by LBDonovan** [comment]
Hmm, ok I'll get on this asap.

One possible temporary workaround if the drag-n-drop upload is working would be to upload the zip into a project via drag-n-drop, then from the IDE console:

`mkdir updates
mv projects/<project>/bela-master.zip updates/
make checkupdate
make update`

**Comment by LBDonovan** [comment]
@giuliomoro just pushed a fix for this (tested only on chrome windows 7 so far, but pretty sure it was the problem) onto the dev branch. Should it maybe go on the master branch instead?
