### ISSUE TITLE
Resources: Clarify OSC example

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#514]
https://github.com/BelaPlatform/Bela/blob/ea5b169e0a1a5ec35421071ab42f0c0cfbfca540/resources/osc/readme.txt#L2

Should state that this is to be run _on Bela_, as might not be obvious if you have cloned the repo locally.

**Comment by giuliomoro** [comment]
Closed 1d04a726c9b780eb5d3e6b132c1dc83922f56130
