### ISSUE TITLE
Slim-down Scope.h for faster compile times

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#52]

**Comment by LBDonovan** [comment]
Could we do this with precompiled headers like you suggested? Either just oscpkt.hh which is what takes the time, or all of them. I guess it would have to be done in the Makefile?

**Comment by giuliomoro** [comment]
I think for the moment we should create a ad-hoc header file for `oscpkt` and only include `oscpkt.hh` in `Scope.cpp`

**Comment by LBDonovan** [comment]
The trouble with that is that oscpkt.hh needs to be included in Scope.h and OSCServer.h/OSCClient.h which are also both included in Scope.h. Without doing this there is no way to parse OSC messages from render.

And separating oscpkt into a .h and a .cpp is not trivial.

So I think precompiled headers probably are the way to go. I'm looking into it now.

**Comment by giuliomoro** [comment]
@LBDonovan so are you looking into pre-compiled headers?

**Comment by LBDonovan** [comment]
I did look into it. Turns out it's pretty hard to make them work. I can get clang to compile a .gch file from the command line easily enough, but it either doesn't seem to work or have any effect on the compile time.

**Comment by giuliomoro** [comment]
this was done at some point
