### ISSUE TITLE
Memory leak in sample-streamer

### ISSUE THREAD

**Issue by tommessick** [BelaPlatform/Bela#527]
The sample streamer example stops running after about 10 minutes with an out-of-memory error showing is syslog.  In SampleLoader.h the variable tempBuf is allocating memory with new() and never freeing it.  Adding "delete[] tempBuf;" lets the example without the memory usage growing.

**Comment by giuliomoro** [comment]
good one. @adanlbenito can you apply this there and all the other examples that include `SampleLoader.h` ? 
```
$ find examples -name SampleLoader.h
examples/04-Audio/sample-loader/SampleLoader.h
examples/04-Audio/sample-piezo-trigger/SampleLoader.h
examples/04-Audio/sample-streamer/SampleLoader.h
examples/11-Extras/audio-capelet-test/SampleLoader.h
```
