### ISSUE TITLE
IDE: clickable warning/errors from the compiler cause problems if they are relative to files other than the one currently opened

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#528]
Say you have two files in the current project, and file  A has an error, but file B is currently open and you try to build, you will get an error with a clickable link to file A:linewhatever, but when you click it you get an error message "Error opening file. Please open a different file to continue". This seem now to happen also for errors/warnings in the core code, thus replacing the behaviour in #145.

**Comment by TheTechnobear** [comment]
even if you switch to that file, click on the error will still give you the same issue...
makes it quite tricky to work with many files, as you can't click on errors to fix them quickly

**Comment by giuliomoro** [comment]
this has been fixed in topic/lib-gui-merge (soon to be released)
