### ISSUE TITLE
Bela/Pd/Pulse Sensor Not Running on External Power

### ISSUE THREAD

**Issue by cwaskowi** [BelaPlatform/Bela#539]
I'm working on a project where a pd patch plays two tracks generated from the data of two pulse sensors (from pulsesensor.com) 
I'm running the data through an Arduino Teensy LC to slow it down before going to the Bela (the sensors were a bit too sensitive when just plugged into the Bela.) Everything works fine when it's plugged into my computer, but when I try to run the project on the Bela's boot and power it with an external 5V power source, nothing runs - the pulse sensor's lights don't even turn on.
Does anyone have any experience working with this or a similar combination of sensors/controllers?
Attaching the files for clarity. Thanks!!
![screen shot 2019-02-26 at 1 35 05 pm](https://user-images.githubusercontent.com/37230962/53437401-6f4d6c00-39cb-11e9-8fcc-6d074179092a.png)
![screen shot 2019-02-26 at 1 35 28 pm](https://user-images.githubusercontent.com/37230962/53437402-6fe60280-39cb-11e9-8262-9b40e18ac141.png)
![screen shot 2019-02-26 at 1 35 35 pm](https://user-images.githubusercontent.com/37230962/53437403-6fe60280-39cb-11e9-918d-050589827862.png)

**Comment by giuliomoro** [comment]
what's the current rating of the external power supply ? How is the Teensy powered?
Does the Bela board turn on when powered from the external power supply? How are you providing power to Bela? Is this Bela or Bela Mini?

This question should be moved to forum.bela.io

**Comment by cwaskowi** [comment]
External power supply is 5V barrell, Teensy is powered directly to the Bela
board via breadboard, bela turns on and it's a normal Bela, not a mini

**Comment by giuliomoro** [comment]
then what is it that is not turning on? The "Pulse sensor"? What is it? How is it powered?

> What is the current rating of the external power supply?

That is, what is the Ampere rating specified on the PSU?

**Comment by giuliomoro** [comment]
@cwaskowi any update on this ? can I close it?
