### ISSUE TITLE
write-file example not stopping. aux tasks not killed?

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#54]
<img width="872" alt="screen shot 2016-08-03 at 16 14 34" src="https://cloud.githubusercontent.com/assets/11576979/17370817/6fa34170-5995-11e6-87a5-e38b247d87c0.png">

**Comment by giuliomoro** [comment]
This may be a regression ... I thought it was fixed.

**Comment by giuliomoro** [comment]
I fixed this by making sure that the auxiliary task does not suspend itself after the main thread has called `rt_task_join` on it (i.e.: checking for `!gShouldStop` before suspending).
@apmcpherson does it look ok to you? 9f50ddf

**Comment by apmcpherson** [comment]
Looks like a fine solution to me.
