### ISSUE TITLE
Arbitrary pins comment

### ISSUE THREAD

**Issue by paulelong** [BelaPlatform/Bela#557]
I noticed in the using the arbitrary pins section it mentions "However, you can disable the digital I/O in Bela".  After some looking around and testing, I discovered that "Use Digital" in settings might be the option you are talking about.  Can describe how to disable the digital I/O so you can use those pins from a stand alone C++ app?

**Comment by giuliomoro** [comment]
that's correct: untick the tickbox "Use digital" in the IDE. Or, if you are using the command line, use the `-G 0` flag.
