### ISSUE TITLE
update_board script does not remove deleted examples

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#56]
In the dev-capelet branch, I removed the multiplexer example to replace it with two others of different names. Running update_board leaves the old, stale example in place.

Not removing things is a good plan when it comes to user projects (!) but could be problematic elsewhere in the core code.

**Comment by giuliomoro** [comment]
I cannot reproduce this, `update_board` should completely replace all of these  files/ folders, and it does for me 
`core include Makefile libNE10.a libprussdrv.a examples Doxyfile`

**Comment by giuliomoro** [comment]
Confirmed, when updating through the IDE

**Comment by giuliomoro** [comment]
Was stale in some branches. Fixed.
