### ISSUE TITLE
Performance monitor document /proc/xenomai/stat path incorrect

### ISSUE THREAD

**Issue by paulelong** [BelaPlatform/Bela#561]
The perf documentation the locations of stats is /proc/xenomai/stat, but I don't see that directory.  Instead I do see stat in /proc/stat.  Should the documentation be fixed to point to this alternate location?

**Comment by giuliomoro** [comment]
That's the path for images < v0.3 . Now it is `/proc/xenomai/sched/stat`. I fixed the wiki
