### ISSUE TITLE
IDE: add support for multiplexer capelet

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#57]
On the dev-capelet branch, the -X command-line option has been added for enabling the multiplexer capelet. It should be added to the Settings tab on the IDE. The valid options are:

(default / not provided) -- no multiplexer capelet enabled
-X 2 -- 2 channels per analog input (16 total)
-X 4 -- 4 channels per analog input (32 total)
-X 8 -- 8 channels per analog input (64 total)

Using the multiplexer capelet requires analog input enabled with 8 channels.

**Comment by giuliomoro** [comment]
Great.
I see how it would be useful to have the analogs set to 4 channels, so that 2 are used for multiplexing and 2 are used at 44.1kHz (e.g.: in conjunction with the audio capelet). 
Is this feasible via software?

**Comment by apmcpherson** [comment]
4 channels at 44.1kHz is possible but not straightforward. 

The multiplexer capelet has one set of selector pins for channels 0-3, another set for channels 4-7. It takes time for the signal to settle after the channel is changed, so it reads one set of inputs while the other set is settling. If you use only 4 channels, then right now that means channels 0-3, which are all on the same selector pins. Therefore there would be no time for the inputs to settle when switching channels and crosstalk would be a problem.

To use 4 channels at 44.1kHz with the mux, it would have to be channels 0, 1, 4 and 5. This could be done but requires different PRU code. It would be useful but I think it's not a high priority at the moment.
