### ISSUE TITLE
adding scope library causes the error 'reference to 'map' is ambiguous'

### ISSUE THREAD

**Issue by JacobTFH** [BelaPlatform/Bela#571]
I'm trying to add a scope to a project based on the trill-craft-oscillator-bank example, but when I include the Scope library, I get the error `reference to 'map' is ambiguous`

**Comment by JacobTFH** [comment]
ok on closer inspection, the problem occurs when `SampleLoader.h` and `SampleData.h` (from the  sample-piezo-trigger example) are used. Removing either the Scope library or these two libraries gets rid of the problem

**Comment by giuliomoro** [comment]
Yeah, that's because those two header files are silly and contain `namespace std;`. That has to be removed and compensated for. Same as was done for be1b5c6f2917e72b023c3b20269d8338fa5b9ad8

**Comment by giuliomoro** [comment]
fixed now in the examples in SampleLoader.h and the likes in 5714989c57a1554c21c88588f074f224b5491931
