### ISSUE TITLE
Should we support C++14 by default?

### ISSUE THREAD

**Issue by LBDonovan** [BelaPlatform/Bela#59]
Is there any reason not to do this?

It would just involve adding the flag -std=c++11 to the compiler line in the Makefile.

**Comment by apmcpherson** [comment]
Probably it would be okay, but it might have unexpected implications for existing projects, so should be saved until the next major update.

**Comment by giuliomoro** [comment]
maybe only for the users provided files ?

**Comment by LBDonovan** [comment]
What's the disadvantage to compiling the core with C++11?

I have a prototype user I2C library that uses C++11 that I would like to include in the core.

**Comment by giuliomoro** [comment]
It should be fine, actually. I take it if you do not use any C++11 features it will mostly not cause anyt troubles (except maybe `const` vs `constexpr` ?).

**Comment by LBDonovan** [comment]
According to [this](http://clang.llvm.org/cxx_status.html) c++14 is supported since clang 3.4 so we may as well got for that. Can we simply add `-std=c++14` to the makefile? I think some features are missing from gcc 4.9 but I don't think that is a problem.

**Comment by giuliomoro** [comment]
Also clang 3.9 is available as a binary

**Comment by LBDonovan** [comment]
What do we gain from that? Sounds a bit risky...

**Comment by giuliomoro** [comment]
```
In file Midi.cpp: non-constant-expression cannot be narrowed from type 'int' to 'midi_byte_t' (aka 'unsigned char') in initializer list [-Wc++11-narrowing] column: 63, line: 410
```

**Comment by giuliomoro** [comment]
Done, though this may later require refactoring most of the examples so that the `signed unsigned comparison` stops bothering us. Or maybe just add the appropriate flag to the Makefile so that it is ignored.

**Comment by LBDonovan** [comment]
Porque no -std=c++14?

**Comment by giuliomoro** [comment]
Probably because c++11 is what the issue name called for ... ?

**Comment by LBDonovan** [comment]
O rly?

**Comment by LBDonovan** [comment]
Seriously though we should do c++14, there's no reason not to. And I've been eyeing up this library which requires it:

http://libsignal.io

(actually I thought it did but it turns out its just c++11)

**Comment by apmcpherson** [comment]
+1 for suppressing the signed/unsigned warning. It makes our example code look more complex when every loop needs unsigned ints to work.
