### ISSUE TITLE
Csound Examples and Csound COSMO Not Working on Bela or Bela Mini

### ISSUE THREAD

**Issue by csounder** [BelaPlatform/Bela#606]
bash: line 1:  5157 Segmentation fault      belacsound --csd=/root/Bela/projects/exampleTempProject/_main.csd 2>&1
Makefile:579: recipe for target 'runide' failed
make: *** [runide] Error 139
Bela stopped

NOTE that the C++-libCsound examples do work.

**Comment by giuliomoro** [comment]
confirmed. What version of the board / Bela code are you on? I am using the latest `dev` with in addition this updated csound http://eecs.qmul.ac.uk/~gm303/csound-6.14-bela.deb

**Comment by csounder** [comment]
It just arrived two days ago.  I presume it is the latest.  Can you update the git repo with the latest working version of Csound that you recently built.  I think the repo has an earlier build.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
I am on:  Bela image, v0.3.7b, 25 November 2019

**Comment by csounder** [comment]
As you know, your latest dev builds with csound 6.12 - do I just swap the csound 6.14 for the 6.12 and run update again? or do I need to change something in a makefile as well?

**Comment by giuliomoro** [comment]
if you are comfortable with the terminal, you can copy the file linked above to your board and then install it using `dpkg`.

For instance, from a mac/linux terminal you would do:

```
curl http://eecs.qmul.ac.uk/~gm303/csound-6.14-bela.deb -o /tmp/csound-6.14-bela.deb
scp /tmp/csound-6.14-bela.deb root@bela.local:
ssh root@bela.local dpkg -i csound-6.14-bela.deb
```

If the above seems like gibberish to you (or you are on Windows), then I can guide you through how to do it without terminal, just let me know

**Comment by csounder** [comment]
THANK YOU!!!! I am happy to report that... when using your latest dev by and simply replacing the csound6.12beta build with your latest csound6.14 build and then running your update script again.... it WORKS!!!  Super happy about being able to just work with my Csound code directly on the bela and bela mini - with my students at Berklee

**Comment by csounder** [comment]
I did this work on my bela mini starter kit, but... to learn, I will use your command-line approach to update my bela starter kit.

**Comment by giuliomoro** [comment]
I added the updated build to the `master` and `dev` branches, so that it can be rolled out in the next release image.
