### ISSUE TITLE
Crashes when building a new Csound Project

### ISSUE THREAD

**Issue by csounder** [BelaPlatform/Bela#609]
Using the latest build of Csound 6.14 and the latest update from dev, I am happy to report that ALL the Csound and Cosmo examples are working... BUT... when I attempt to build a new Csound project and run from the init  "_main.csd" it builds/renders and makes a short bit of sound and then crashes.
```
Building project ...
Build finished
Running project ...
WARNING: [mError opening plugin directory '/usr/local/lib/csound/plugins-6.0': No such file or directory[m
[m0dBFS level = 32768.0
--Csound version 6.14 (float samples) Feb  9 2020
[commit: 1073b4d1bc2304a1e06defd266781a9c441a5be0]
libsndfile-1.0.27
   0"000.146| WARNING: [main] duplicate call from main program to xenomai_init() ignored
   0"000.382| WARNING: [main] (xeno-config --no-auto-init disables implicit call)
   0"066.646| WARNING: [main] duplicate call from main program to xenomai_init() ignored
   0"066.802| WARNING: [main] (xeno-config --no-auto-init disables implicit call)
realtime mode enabled
UnifiedCSD:  /root/Bela/projects/test/_main.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
realtime mode enabled
sorting score ...
	... done
setting dummy interface
displays suppressed
0dBFS level = 1.0
orch now loaded
audio buffered in 256 sample-frame blocks
SECTION 1:
Initialising spinlock...
Starting realtime mode queue: 0xb4bba010 thread: 0x10fee10
backtrace() returned 0 addresses
Csound tidy up: Segmentation fault
backtrace() returned 0 addresses
Csound tidy up: Segmentation fault
Makefile:581: recipe for target 'runide' failed
make: *** [runide] Error 1
Bela stopped
```

**Comment by giuliomoro** [comment]
what is the content of the script you are trying to run?

**Comment by csounder** [comment]
Basic .csd files do run.  Thanks for your help with this.
_____________________________________________
*Dr. Richard Boulanger*
Professor of Electronic Production and Design
Professional Writing and Music Technology Division
Berklee College of Music
______________________________________________
OFFICE: 1126 Boylston St., Suite 201 (EPD), Suite 208 (Boulanger)
______________________________________________
President of *Boulanger Labs* - http://boulangerlabs.com
Author & Editor of *The Csound Book* -
http://mitpress.mit.edu/books/csound-book
Author & Editor of *The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book
______________________________________________
about: http://www.boulangerlabs.com/#about
about: http://www.csounds.com/community/developers/dr-richard-boulanger/
music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/
______________________________________________
email: rboulanger@berklee.edu
facebook: https://www.facebook.com/richard.boulanger.58
