### ISSUE TITLE
How to find/include samples & scanned matrix files in a .csd - where to put them?

### ISSUE THREAD

**Issue by csounder** [BelaPlatform/Bela#611]
Thanks to your help, I am now running all sorts of Csound .csd files in the project - MIDI instruments and note-list based instruments and pieces.  As you suggested, simply changing their names to _main.csd does the trick.  BUT... files that include samples or scanned matrix files do not "find" the sample.  Even when I specify a full path from the Desktop on my MacBook Pro.  Can you advise me on where I need to place the samples so that a .csd file can find them or what is the specific path that I should use?

**Comment by giuliomoro** [comment]
For a project called `PROJECTNAME`, project files are stored on the board at `/root/Bela/projects/PROJECTNAME/`, and the Csound program is started as following:

```
cd /root/Bela/projects/PROJECTNAME && belacsound --csd=_main.csd
```

Knowing this, you should be able to use relative paths or absolute paths as you wish.

PS: this is not properly a github issue, and would be best suited on forum.bela.io

**Comment by csounder** [comment]
Yes.  I discovered that the forum might be the place for this and several other discussions/issues/suggestions that I would like to make.  We are getting ready to make Belas a part of my curriculum at Berklee and I am trying to prep all the materials.  Thanks.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by giuliomoro** [comment]
that's exciting news!
