### ISSUE TITLE
Segmentation fault in sample-streamer example

### ISSUE THREAD

**Issue by divingpetrel** [BelaPlatform/Bela#613]
I'm getting a segmentation fault error when loading a different **wav** file in the sample streamer example.

https://github.com/BelaPlatform/Bela/tree/master/examples/Audio/sample-streamer

`make: * [run ide] Error 139 Bela stopped`

scp'd the wav file from terminal to the examples folder..

thanks

**Comment by giuliomoro** [comment]
how many audio channels are there in your file? The example only works for stereo files. You should be able to fix that by amending the `NUM_CHANNELS` define.

**Comment by divingpetrel** [comment]
the file is stereo and NUM_CHANNELS=2

**Comment by giuliomoro** [comment]
would you be able to share your file?

**Comment by divingpetrel** [comment]
It's working with wav files <= 16 bit 

All good thanks

**Comment by giuliomoro** [comment]
it's weird, it seems to be a libsndfile issue. Could you please provide a file that triggers the issue?

**Comment by divingpetrel** [comment]
https://drive.google.com/file/d/1o851Py_Ypg9HonPfoxeK_2gDVFIB8It2/view?usp=sharing

**Comment by giuliomoro** [comment]
thanks, I will have a look
