### ISSUE TITLE
IDE: when building, show .S files in list 

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#618]
When compiling a project, assembly (.S) files are not listed as the build goes along unless there is an error in the file.

For example, if I change `render.cpp`, I will see `Building render.cpp...` when I click the build button. But if I change `myfile.S`, I will not see it built in the console even though the compile is taking place -- unless there is an error in the file.

**Comment by giuliomoro** [comment]
It's weird, because:

```
# Rule for user-supplied assembly files
$(PROJECT_DIR)/build/%.o: $(PROJECT_DIR)/%.S
    $(AT) echo 'Building $(notdir $<)...'
#   $(AT) echo 'Invoking: GCC Assembler'
    $(AT) as  -o "$@" "$<"
    $(AT) echo ' ...done'
    $(AT) echo ' '
```

**Comment by giuliomoro** [comment]
so I think it's not actually re-building it .

**Comment by giuliomoro** [comment]
Oh actually I see what is happening: it is being compiled during syntax check.

**Comment by giuliomoro** [comment]
fixed in `dev`.
