### ISSUE TITLE
passwd giulio user

### ISSUE THREAD

**Issue by Doray** [BelaPlatform/Bela#625]
what is the password for the user giulio on Bela ? why does deluser not work ?

**Comment by giuliomoro** [comment]
I don't think there is a user `giulio` on Bela, which would explain why `deluser` doesn't work. Where do you see that such a user exists?

**Comment by Doray** [comment]
root@bela:~# ls /home
giulio
root@bela:~#

**Comment by Doray** [comment]
root@bela:~# ls /home
giulio
root@bela:~#

**Comment by Doray** [comment]
i don't know why it is striken through

**Comment by giuliomoro** [comment]
oh that's funny, no idea how it got there, anyhow there is no user `giulio`, as you can see from, e.g.: `getent passwd`. I logged the issue [here](https://github.com/BelaPlatform/bela-image-builder/issues/95)

**Comment by giuliomoro** [comment]
> i don't know why it is striken through

The `~` in markdown enables strikethrough. The lines you pasted looked like this:

```
root@bela:~# ls /home
giulio
root@bela:~# 
```
so it  is striking through from the first to the second `~`, and the `~` symbols themselves are not displayed. To avoid this, here or in the Bela forum, you should include these lines in triple backticks (\`\`\`\), and you'd get something like this:


```
root@bela:~# ls /home
giulio
root@bela:~# 
```
