### ISSUE TITLE
csound6~ installed on Bela with PD

### ISSUE THREAD

**Issue by csounder** [BelaPlatform/Bela#638]
As you know, the latest csound6~ (csoundapi~) runs all of Csound inside of PD.  If you would install or include this external with PD, then csound would run in PD and your Trill Examples (for PD) could be used to run Csound (from within PD).  Currently, this external will not run with the version of PD that is installed - one cannot drag the external to the project folder to include it, one cannot run the PD csound~ examples from csound.com on the Bela - it would be helpful if one could do this.

https://github.com/csound/csound_pd/releases
http://write.flossmanuals.net/csound/a-csound-in-pd/

https://github.com/csound/csound_pd

On Ubuntu Linux, you can install the csound6~ via the Synaptic Package Manager. Just look for "csound6~" or "pd-csound", check "install", and your system will install the library at the appropriate location. If you build Csound from sources, go to https://github.com/csound/csound_pd and follow the build instructions. Once it is compiled, the object will appear as csound6~.pd_linux and should be copied (together with csound6~-help.pd) to /usr/lib/pd/extra, so that PD can find it. If not, add it to PD's search path (File->Path...).

**Comment by giuliomoro** [comment]
great. It was straighforward to build. I added it [here](https://github.com/BelaPlatform/Bela/issues/621), feel free to try it out.
