### ISSUE TITLE
Error while generating Doxygen documentation

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#64]
Got this output while running `update_board` from latest .git

I can try to debug further if you want to give me instructions

```
Checking the board is up and running at root@192.168.7.2...done
Updating the Bela core code in root@192.168.7.2:~/Bela
All the changes to the CORE files in the remote folder ~/Bela will be LOST. The content of these files/folders will be lost:
  core include Makefile libNE10.a libprussdrv.a examples Doxyfile samples
Your projects stored in ~/Bela/projects should be safe (and surely you have already backed them up somewhere safe, haven't you?).
Are you sure you want to continue? (y/N) y
Updating Bela core files to remote folder ~/Bela
Stopping Bela...done
Updating files...Updated files: 0 ...done
Creating directory structure on BeagleBone...done
Generating on-board documentation...
Error while generating Doxygen documentation
```

**Comment by jarmitage** [comment]
Possibly a false alarm as I need to update the entire image on my Bela. Will check back!

**Comment by giuliomoro** [comment]
thanks Jack, I cannot reproduce this.

Can you please 
- clear your terminal ( probably command+K) and then
```
ssh root@192.168.7.2
cd Bela
doxygen
```
and post the output?

Also, can you confirm  this works?
```
./update_board -d 

```
it skips generating documentation

**Comment by jarmitage** [comment]
Hi Giulio,

I am updating the image first to see if that eliminates the issue. If it persists I will try what you have requested, and if it works I will close the issue.
