### ISSUE TITLE
xenomai_init() ignored and xeno-config --no-auto-init disables implicit call

### ISSUE THREAD

**Issue by csounder** [BelaPlatform/Bela#640]
When running Csound on the Bela, we get the following warnings in the console.  Are these important?  Are they affecting the performance any?

 0"068.045| WARNING: [main] duplicate call from main program to xenomai_init() ignored
   0"068.566| WARNING: [main] (xeno-config --no-auto-init disables implicit call)

**Comment by giuliomoro** [comment]
duplicate of https://github.com/BelaPlatform/Bela/issues/612 , no this does not cause any problem, but would be nicer to get rid of it. Please continue discussion there if appropriate.
