### ISSUE TITLE
Files from sub-folders missing when downloading project as zip file

### ISSUE THREAD

**Issue by mattybrad** [BelaPlatform/Bela#649]
When downloading a project from the IDE, the files which were present in sub-folders in my project were not present in the zip file. Otherwise awesome system though!

**Comment by giuliomoro** [comment]
oh. Support for subfolders has been added only recently, and this part was left out clearly. Should be an easy fix, thanks for raising it.

**Comment by giuliomoro** [comment]
Indeed 6cc6ec33215caec1d02041a2dcf99968e309514a
