### ISSUE TITLE
IDE: going from C++ to Pd within a project fails

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#67]
To reproduce:

1. Start with a C++ project. 
2. Upload a _main.pd file. This will have no effect because there is a render.cpp file in the project.
3. Delete render.cpp.

After this, the project will continue to run with the old render.cpp code rather than using the uploaded Pd file.

**Comment by LBDonovan** [comment]
@giuliomoro is this something to do with how the Makefile detects if a project is a libpd project? 

Presumably cleaning the project fixes this?

**Comment by giuliomoro** [comment]
It has to do with the fact that `make` only looks at modified `.cpp` and `.c` files. When you remove `render.cpp`, then `make` does not see any cpp files, so it thinks the project is up-to-date and does not re-compile it. If you delete the executable and you force it to re-link, it will see the .pd file and try to link in `default_libpd_render.cpp` and you will probably get a linker error for duplicated symbol "render", which is better than nothing.

I am not sure what the best approach is. This is not something that make can easily handle. One way would be for the IDE to delete the corresponding `.o` file and the executable every time you delete a `.cpp` file

**Comment by giuliomoro** [comment]
this should be fixed by 8743fec , to be re-tested

**Comment by giuliomoro** [comment]
Confirmed fixed by 8743fec

**Comment by giuliomoro** [comment]
It's still up to the user to delete any old, non-libpd-compatible `render.cpp` file, but we cannot do much about this (actually we could check if the object file that contains the symbol to `render()` does contain any call to the libpd API, but not sure it is worth it.)
