### ISSUE TITLE
Error in symlink in resources for libmathneon

### ISSUE THREAD

**Issue by DhruvaG2000** [BelaPlatform/Bela#670]
Fix symlink in https://github.com/BelaPlatform/Bela/blob/dev-next/resources/wheezy/deb/libmathneon-dev_1.0-1_armhf.deb from 
`../../stretch/deb/libmathneon-dev_1.0-1_armhf.deb` to `../../stretch/deb/libmathneon-dev_1.0.2-1_armhf.deb `

**Comment by giuliomoro** [comment]
fixed, although we haven't shipped a Wheezy image in 4 years, so we should probably consider it unsupported by now :)
