### ISSUE TITLE
Add support for supercollider to Makefile

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#68]
if there is a .scd file, then it should just run sclang now that you can 
https://github.com/sensestage/supercollider/commit/bc43f71412928b1d62dd4176ff3af98d95b08ded

**Comment by giuliomoro** [comment]
Done d4f216a , build a project containing an `.scd` file and it will try to load `_main.scd` with sclang. This could be changed so that if there is only one file, it runs that and in case of multiple files it looks for `_main.scd`.
Alternatively / in addition, a default `_main.scd` file could be provided that "imports" all the `.scd` files in the folder.

Issue that remains is that when you  run it, two distinct `sclang` processes show up in `/proc/xenomai/stat` and `make stop` does not correctly stop a running process.

**Comment by giuliomoro** [comment]
I think the two "sclang" instances are actually two different things:
- one is the sclang that you start from terminal (`sclang /path/to/file.scd`)
- the other one is scsynth that is started from within the above sclang. I believe this is a pthread automatically wrapped by xenomai , that is why it shows up with the same name.

The issue here is that the usual `make stop` command does
`grep $(BELA_AUDIO_THREAD_NAME) /proc/xenomai/stat .....`
to find out what the audio-thread name is, then sends a SIGKILL to it. Once that thread stops, the `scsynth` that wraps it will die as well (because of `gShouldStop`, I think). But of course, the `sclang` that invoked `scsynth` has no reason to die.
Now, there probably is a workaround from the  SC code, e.g.: exit when scsynth returns, but if this is left to the user's `.scd` file, then we can find ourselves in the situation where there is an `sclang` instance running somewhere and we try to start another one, which will fail.
Additionally, if the project is started by the IDE, it will not return when `scsynth` is killed.
On the other hand, running another (non-SC) Bela program will work just fine.

@LBDonovan how does the IDE kill the process it owns when you run it within the IDE? Sending sigterm from the terminal works fine to kill a process running in the IDE, but hitting the stop button does not quit sclang ...
I guess you are calling `make stop`, but should we not (also, first) try to stop the current Bela program process which was spawned by node?

**Comment by LBDonovan** [comment]
The IDE spawns processes using make runide and kills them using make stop. It just holds on to the make process, not the underlying Bela program. The run button won't stop spinning until the make runide process dies, so there must be something blocking that.

**Comment by giuliomoro** [comment]
Yes `killall sclang` would work.
