### ISSUE TITLE
Website broken link

### ISSUE THREAD

**Issue by chaosprint** [BelaPlatform/Bela#698]
Hi,

I am trying to read some docs here:

https://learn.bela.io/using-bela/technical-explainers/scripts/#build_pd_hvccsh

But this link points to nowhere:
https://learn.bela.io/tutorials/pure-data/advanced/heavy-compiler/

Could you please fix this? Thanks.

**Comment by giuliomoro** [comment]
Thanks, now fixed. Here is the correct URL: https://learn.bela.io/tutorials/pure-data/advanced/using-the-heavy-compiler/
