### ISSUE TITLE
SIGXCPU when running a project with analogue disabled

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#7]
@LBDonovan said:

> Run any simple project with analogue disabled (use flag -N0) and no audio is heard, the program crashes with SIGXCPU (CPU time limit exceeded). This is happening because the PRU's COMM_BUFFER_FRAMES value gets set to context.analogFrames in PRU.cpp, which is set to 0 when analogue is disabled. As a result the PRU can never break out of its write loop, and never reaches WRITE_LOOP_DONE. This causes the C++ program to hang until it is killed by Xenomai.
> 
> Overriding the setting of COMM_BUFFER_FRAMES in PRU.cpp and forcing it to the default value of 8 causes the audio to work for approximately 4 seconds, but the program still dies with SIGXCPU, so there must be another problem somewhere in the PRU code when analogue is disabled.

NOTE: below we are referring to commits on the old repo https://code.soundsoftware.ac.uk/projects/beaglert/repository

Issue first appears in commit 52
Commits 47-51 are not working for me at the moment (they use interrupts)
Commits up to 46 (inclusive) do not show this bug. Note that up to commit 46, numAudioFrames is erroneously set to 0 if the analog channels are disabled, so for instance in order to run commit 46 with matrix disabled you need to 
-- select project basic
-- in render.cpp replace 

```
for(int n = 0; n < numAudioFrames; n++) {
```

with

```
for(int n = 0; n < 16; n++) {
```

-- run with -m0

Also note that there is NO change in the PRU code between rev 46 and 52.

**Comment by giuliomoro** [comment]
The workaround in b0f8cb5 overrides analog_enabled, making sure it is alway set to true, then it makes sure that the PRU does not know that the analogs are disabled. Also memory is allocated as if analog were active.
It also makes sure that the BelaContext contains the values it will show when the bug is fixed:
when the context is passed to setup() and render(), it is set
```
context->analogFrames=0;
context->analogInChannels=0;
context->analogOutChannels=0;
```
which also prevents `PRU::loop()` from wasting CPU cycles converting the ``disabled'' channels.

**Comment by LBDonovan** [comment]
I haven't had a chance to look at the new workaround, but I managed a while ago to track down the problem to line 545 in PRU.cpp:
`RTIME sleepTime = PRU_SAMPLE_INTERVAL_NS * (analogChannels / 2) * context->analogFrames / 4;`
The problem being that with analogue disabled, analogChannels is set to 0 and so the audio thread does not sleep when waiting for the PRU, causing the SIGXCPU. I fixed it temporarily by replacing analogChannels with a literal 8 on that line.

The same thing happens on line 780:
`// Wait two buffer lengths for the PRU to finish
rt_task_sleep(PRU_SAMPLE_INTERVAL_NS * context->analogFrames * 4 * 2);`
Though this does't really cause any problems that I can see.

I guess your workaround forces analogFrames to be non-zero?

**Comment by giuliomoro** [comment]
my workaround actually forces analogFrames to be 0 only where  the context is passed to the user and leaves it unaltered otherwise, so when it goes through line 545 it is set to the ``actual'' number of channels/frames. Yet when it comes to line 780 it is set to 0, but that should not cause any troubles.

**Comment by giuliomoro** [comment]
Suggested a fix for this, better than the previous workaround.
	d610c23

The issue was in two places:
* the sleepTime was 0 (causing SIGXCPU)
* the PRU was passed `pru_buffer_comm[PRU_BUFFER_FRAMES] = context->analogFrames;`, which is 0 for analog.

Another thing we should decide on is:
what should happen to ***Channels ***Frames ***SampleRate when digital, analog or audio are disabled?
I see three options:
```
Channels = 0;
Frames = 0
SampleRate = 0
```
this cause troubles if you are doing things such as `numAudioFramesPerAnalogFrames` or 1/SampleRate.

an alternative is 
```
Channels = 0;
Frames = `actual`
SampleRate = `actual`
```

Yet another alternative is 
```
Channels = `actual`;
Frames = `actual`
SampleRate = `actual`
```
this would imply allocating (not much) memory for all the buffers, but the code could then run unmodified. We would still save the CPU time of converting back and forth by checking an "analogEnabled" flag.

**Comment by giuliomoro** [comment]
Regression in cdbb557f6b8108101ff37679fa35090a7a6adf54
