### ISSUE TITLE
IDE: missing space in dialog

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#704]
<img width="648" alt="Screenshot 2022-11-11 at 18 31 34" src="https://user-images.githubusercontent.com/4260604/204605309-b72ec6ba-ccbd-48fe-b8d0-7300839208bf.png">

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by giuliomoro** [comment]
@himanshu007-creator 
sure go ahead - if you are for real.

**Comment by himanshu007-creator** [comment]
@giuliomoro, i also wanted to ask how can i start the dev server of Bela in my local environment for futrue contributions?

**Comment by giuliomoro** [comment]
ok thanks. 

copy `IDE/ide-dev.js.template` to `IDE/ide-dev.js` and adjust parameters there accordingly, then you can run `gulp local` from `IDE/`. I use `node v8.12.0` via `nvm` for development. Sometimes `gulp local` doesn't run so I do `./node_modules/gulp/bin/gulp.js local` and that does the trick

**Comment by himanshu007-creator** [comment]
Thanks I'll keep that in mind. Happy new year✨
