### ISSUE TITLE
basic-midi example has mode switches

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#72]
... which are brilliantly outlined by the newest IDE !

**Comment by TheTechnobear** [comment]
would it be possible to get the IDE to display a running total of mode switches?
(woud be useful during development, perhaps optional like cpu?!)

**Comment by giuliomoro** [comment]
In the dev branch (or in the scope-dev branch ?) you get a message on the log window when a mode switch takes place in the audio thread. Ironically, CPU monitoring and mode switches monitoring has quite some impact on CPU usage.

Also, we are currently monitoring mode switches from an external utility (polling the Xenomai API), while it would be possible to set a hook on the audio-thread itself to call a function  every time there is a mode switch, which could arguably be better.

You say thy are confusing as they are now, how would you want them to be? Similarly to the CPU indicator?

Incidentally, you can get CPU usage and mode switches for cheaper and with more detail from the command line, see [here](https://github.com/BelaPlatform/Bela/wiki/Performance-monitor) how.

**Comment by LBDonovan** [comment]
Hmm, I think saying that monitoring the CPU usage from the IDE has _quite some_ impact on CPU usage is a bit of an exaggeration, it generally seems to cause a constant 1-2% increase with occasional peaks up to 3-4%. Thanks to xenomai's magic, this should only have any impact on performance if you're already very close to the limit. This could potentially be optimised and reduced, which I will look into.

It's also worth noting that the IDE gives a cumulative total of Bela's CPU usage, including all aux tasks, the xenomai overhead from the IRQ process, and secondary mode usage scaled correctly according to xenomai's usage ratio, all rolled into a single number, which is not easily available from the command line.

@TheTechnobear to see a running total of mode switches from the IDE, tick the 'xenomai stats' option in the IDE settings, and monitor the MSW column of the 'bela-audio' task. Do you think it would be more convenient to display this number on the toolbar alongside the CPU usage?
