### ISSUE TITLE
IDE: scope should go 'inactive' when it is not receiving live data

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#73]
No need to delete the data that are currently displayed, but, e.g.: set the background color to 0xBBB so you know you are not looking at a live image

**Comment by giuliomoro** [comment]
the fix is fine, though I'd like the scope window to be greyed after it is not triggered for a few seconds, as it is more fool-proof.

**Comment by LBDonovan** [comment]
this now happens in the latest commits on scope-dev
