### ISSUE TITLE
IDE: scope should do oversampling when rendering

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#74]
and it should not be done in the Bela code.
Possibly, scope should have a (default) option for using linear interpolation when visualizing the signal.

**Comment by giuliomoro** [comment]
This from the current scope-dev branch: I believe oversampling is now done in the browser window. You sometimes get this weirdness here when the blocksize is 128: this is the FFT of three sinewaves of frequency 4300. This being the abs FFT, they should all be the same, but they are not? Further to this, there is no reason why there should be a dip instead of a peak.

<img width="1280" alt="screen shot 2016-08-18 at 04 17 50" src="https://cloud.githubusercontent.com/assets/4260604/17760923/150d40fa-64fb-11e6-9dfe-da177803a6b6.png">

**Comment by LBDonovan** [comment]
This should be fixed I think?
