### ISSUE TITLE
IDE: scope, what is a frameWidth?

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#76]
If I understand correctly, the frameWidth is the number of samples per each channel per each block that is sent from the `Scope` class to node.

If that is correct, it is confusing to call it a frame because we use the same term `frame` with different meaning in, e.g.: `context->audioFrames`

**Comment by LBDonovan** [comment]
Yeah, frameWidth is actually the width of the browser's scope canvas in pixels, and therefore the number of samples the browser is expecting per channel.

It's a private variable hidden from the user so I didn't really give much thought to naming clashes but feel free to change it.

I just pushed the branch I have been working on, scope-dev, it has a new-look ui and some other improvements. If you're digging in to the scope (please do!), probably best to do it on that branch.
