### ISSUE TITLE
Repo folder structure: make it such that it can be cloned to the board

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#77]
is it possible to rearrange the folder structure in such a way that a Bela board connected to the internet could do 
$ git clone git@github.com:BelaPlatform/Bela.git ~/Bela
and be good to go?

This is what I suggest in theory (on case-sensitive file-systems)
```
mv Bela/ide/dev Bela/dev
rm -rf Bela/ide/scripts # (this should be embedded into update_board)
mv Bela/ide/IDE Bela/IDE
```

**Comment by LBDonovan** [comment]
Yes that would be fine. Ideally the dev folder would not appear on the board, but it doesn't matter if it does.

**Comment by giuliomoro** [comment]
yes, that's the spirit
