### ISSUE TITLE
Use poll to detect push button action

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#87]
This would drastically reduce CPU usage and rate of growth of PIDs!
e.g.: https://github.com/BlokasLabs/pisound/tree/master/pisound-btn

**Comment by giuliomoro** [comment]
We can now detect short presses ( 0.06 < t < 2 ) and long presses (t > 2).

What should we do with them?

The long one should be for shutdown, the short one should be user-defined (e.g.: "next patch").

currently I use them to run
`/root/click.sh`
and
`/root/hold.sh`
respectively.

I guess it is just a matter of finding sensible names for the above.

@apmcpherson @LBDonovan suggestions?

**Comment by apmcpherson** [comment]
Two schools of thought: 

(1) Have it do nothing -- accidental bumps are more likely than a deliberate interaction with the button. This was my original choice.

(2) Have it do something useful for development or debugging. Perhaps restart the program without shutting down the whole board?

But if it is user-defined, then I guess people can do what they want.

In terms of name, give them a prefix that makes it clear they are related e.g. `cape_button_click.sh`, `cape_button_hold.sh`
