### ISSUE TITLE
IDE: full documentation link assumes 192.168.7.2

### ISSUE THREAD

**Issue by TheTechnobear** [BelaPlatform/Bela#89]
go to help for something e.g. midi, you will see a full documentation link which takes you to the generated doxygen files.
however, it appears to be hardcoded to 192.168.7.2 rather than a relative link to the site used to access. this will therefore fail if bela is connected via ethernet

(e.g. my hostname for bela is bela2.local , with a 192.168.1.x address on my local network, so it fails)

**Comment by giuliomoro** [comment]
Thanks, should be fixed 8d4645b

**Comment by TheTechnobear** [comment]
fixed, confirmed 👍  thanks
