### ISSUE TITLE
logging-sensors: Sketch can't be stopped once running

### ISSUE THREAD

**Issue by disastrid** [BelaPlatform/Bela#91]
When the example sketch is run it can't be stopped without shutting down the board (this is when using dev branch).

**Comment by giuliomoro** [comment]
Duplicate of #54 .
I believe this was fixed in 9f50ddfbee7889f43148b41cecd3e0e6f62f7386  (dev branch, five days ago).
Can you confirm it is still outstanding?

**Comment by disastrid** [comment]
You're right - I must have updated earlier that day. Thanks! :)
