### ISSUE TITLE
IDE: 67237 mode switches detected on audio thread!

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#92]
Regardless of how we solve the "running number of MSW" mentioned in #72, we need to ensure that the misleading and wrong
```
 67237 mode switches detected on audio thread!
```

is not displayed in the IDE when stopping/restarting a running program.

**Comment by LBDonovan** [comment]
Agreed.

I was thinking about how to reduce the CPU consumption of finding the mode switches - at the moment I'm setting an interval in node every second which execs the mode switch detector binary as a new process. The detector then executes once, prints the number of mode switches to the stdout and exits.

Would it be better to spawn a single process once, which usleeps for a second between printing the mode switches to stdout? Then the overhead of spawning a process every second would be eliminated. Would the usleep have any undesirable consequences?

**Comment by giuliomoro** [comment]
that sounds like a good approach to me.
As mentioned elsewhere, we could add a hook to the Bela program that is executed when a MSW is detected in the audio thread. While that would be overall cheaper, I am not in favor of that because in case of a MSW it would cause extra load to the audio thread, while some people may want to allow MSW programmatically (e.g.: to load a new patch) and we should not add overhead to that.
